steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['run', 'test', '--', '--scope', '${_SCOPE}']
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-f',
        '$_DOCKER_FILE',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
        '--build-arg',
        'SERVICE_NAME=${_SERVICE_NAME}',
        '--build-arg',
        'ENV_CONFIG_FILE_NAME=${_ENV_CONFIG_FILE_NAME}',
        '.',
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
      ]
  # NOTE:`bash -c`を利用しない配列で書くパターンだと、Secret経由の環境変数を埋め込めなかった
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy $_SERVICE_NAME \
        --service-account ${_SERVICE_NAME}-service@${PROJECT_ID}.iam.gserviceaccount.com \
        --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
        --region ${_LOCATION} \
        --memory 2Gi \
        --set-cloudsql-instances=$$LEGACY_MYSQL_INSTANCE \
        --set-env-vars=LEGACY_MYSQL_PASSWORD=$$LEGACY_MYSQL_PASSWORD \
        --set-env-vars=LEGACY_MYSQL_UNIX_SOCKET=$$LEGACY_MYSQL_UNIX_SOCKET \
        --set-env-vars=LEGACY_MYSQL_USER_NAME=$$LEGACY_MYSQL_USER_NAME \
        --set-env-vars=PROJECT_ID=$PROJECT_ID
    secretEnv:
      [
        'LEGACY_MYSQL_PASSWORD',
        'LEGACY_MYSQL_USER_NAME',
        'LEGACY_MYSQL_UNIX_SOCKET',
        'LEGACY_MYSQL_INSTANCE',
      ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    args:
      [
        'gcloud',
        'builds',
        'triggers',
        'run',
        '${_E2E_TRIGGER_NAME}',
        '--branch=${BRANCH_NAME}',
        '--project=${PROJECT_ID}',
        '--region=${_LOCATION}',
      ]
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: 'flyer-import'
  _DOCKER_FILE: 'apps/batch/flyer-import/Dockerfile'
  _ENV_CONFIG_FILE_NAME: '.env.prd'
  _CLOUD_BUILD_REPOSITORY: 'backend'
  _NODE_VERSION: '18.16.0'
  _SCOPE: 'flyer-import'
  _LOCATION: 'asia-northeast1'
  _E2E_TRIGGER_NAME: 'flyer-import-e2e'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_password/versions/latest
      env: 'LEGACY_MYSQL_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_unix_socket/versions/latest
      env: 'LEGACY_MYSQL_UNIX_SOCKET'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_user_name/versions/latest
      env: 'LEGACY_MYSQL_USER_NAME'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_instance/versions/latest
      env: 'LEGACY_MYSQL_INSTANCE'
