steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['run', 'test:e2e', '--', '--scope', '${_SCOPE}']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _NODE_VERSION: '18.16.0'
  _SCOPE: 'description-import'
