const bffStoreData = {
  code: '859',
  name: 'カインズ本庄早稲田店',
  webUrl: 'https://map.cainz.com/detail/859/',
  address: '〒351-0005 埼玉県朝霞市根岸台3丁目20番1号',
  postCode: '351-0005',
  telNumberList: [
    {
      contactName: '本館',
      telNumber: '048-468-0111',
    },
  ],
  businessTime: '9:00〜20:00',
  businessTimeNote: '本館以外は19:00閉店',
  regularHoliday: '1月1日',
  regularHolidayNote: 'その他不定休あり',
  webOpenStoreFlag: true,
  detail: {
    code: '813',
    landscape: {
      latitude: 35.808684,
      longitude: 139.610384,
    },
    floorGuideList: [
      {
        floorGuideOrder: 1,
        floorGuideName: '本館',
        floorGuidePdfUrl:
          'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FPDF%2F859_1_%E6%9C%AC%E9%A4%A8.pdf?alt=media',
        floorGuideUrl:
          'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FJPG%2F859_1_%E6%9C%AC%E9%A4%A8.jpg?alt=media',
      },
    ],
    prefectureName: '埼玉県',
    prefectureCode: '11',
    regionCode: '03',
    regionName: '関東地方',
    openingDate: '2020-09-23T00:00:00Z',
    closingDate: '9999-12-31T00:00:00Z',
    closedMessage: '閉店',
    supportPickup: true,
    supportCredit: true,
    supportPickupInnerLocker: true,
    supportPickupPlace: true,
    supportPickupPlaceParking: true,
    supportBackOrder: true,
    supportGeomagnetism: true,
    geomagnetismMapId: 'b8e3ef31b120404b848aa9fe1f66fc5a',
    supportPocketRegi: true,
    supportCuttingService: false,
    webCuttingServiceUrl: 'https://www.cainz.co.jp/store_cutting/813',
    supportDIYReserve: true,
    webDIYReserveUrl: 'https://reserve.cainz.com/store/813',
    supportDogRun: true,
    webDogRunUrl: 'https://dogrun.cainz.com/',
    supportToolRental: true,
    webToolRentalUrl: 'https://reserve.cainz.com/store/813/',
    showVisitingNumber: 0,
    toCloseSettings: [
      {
        toCloseType: 'message',
        toCloseFrom: '2021-12-29T20:00:00Z',
        toCloseUntil: '2022-01-03T20:00:00Z',
        toCloseMessage:
          '年末年始の営業時間は下記の店舗詳細WEBページからご確認ください。',
      },
    ],
    storeAreaCode: '09',
    storeAreaName: '埼玉第1エリア',
    searchWords: 'あさかｱｻｶアサカ',
    digitalFlyerURL: 'https://www.shufoo.net/pntweb/shopDetail/235839/',
    materialHallExistence: true,
    cultureClassExistence: false,
    cycleParkExistence: true,
    DIYSTYLEFloorExistence: true,
    dogParkExistence: true,
    exteriorPlazaExistence: true,
    foodAreaExistence: false,
    gardeningHallExistence: false,
    greenAdvisorExistence: false,
    petsOneExistence: true,
    reformCenterExistence: true,
    workshopExistence: false,
    storePickupExistence: true,
    supermarketExistence: true,
  },
  announcements: [
    {
      code: '813',
      title: '写真プリントキャンペーン',
      body: "開催日:2023年5月15日~2023年6月19日\rイベント内容:\r昔撮った思い出のビデオテープ …時が経つにつれテープの劣化やハード機器の故障等で観たいときに観れなくなるかもしれません。この機会に大切な動画をDVDに、音楽等をCDにダビングしてみませんか?\r2023年5月15日より2023年6月19日までの期間中、テープ5本以上のご注文で1本980円(税込)でお受け致します。(通常:10本以上のご注文で1本980円)各店サービスカウンターにて承りますので是非ご利用願います。\r問い合わせ先:サービスカウンター受付\r\r<b>くみまちモールあさか</b>\rカインズとイトーヨーカドーと30の専門店がスマートなくらしを応援します。\r<a href='https://cainz-kumimachi-asaka.com/' target='_blank'>詳細はこちら</a>",
    },
  ],
};
const bffProductData = {
  productId: '4549509646952',
  name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
  categoryId: 'c2320',
  imageUrls: [
    'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
    'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
    'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
  ],
  departmentCode: '014',
  lineCode: '221',
  classCode: '1400',
  description: '',
  applicableStartDate: '2023-05-24T02:00:10.000Z',
  salesStartDate: '2023-05-24T02:00:10.000Z',
  consumptionTaxRate: 10,
  consumptionTaxCategory: '',
  salesEndDate: '2023-05-24T02:00:10.000Z',
  salesEndFlag: false,
  designatedPharmaceuticalCategory: '0',
  liquorCategory: '0',
  tobaccoCategory: '0',
  hazardousMaterialFlag: false,
  medicalEquipmentClass: '',
  poisonousDeleteriousSubstanceCategory: '0',
  poisonousDrugCategory: '0',
  agriculturalChemicalCategory: '0',
  animalDrugCategory: '0',
  warrantyIssuanceCategory: '0',
  pharmaceuticalFlag: false,
  salesTypeCategory: '0',
  warrantyCategory: '0',
  warrantyPeriod: '1年間',
  deliveryChargeCategoryEc: '0',
  onlineFlagEc: true,
  onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
  onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
  consumptionTaxCategoryEc: '0',
  onlineSalesCategoryEc: '0',
  individualDeliveryChargeEc: 600,
  setProductFlag: false,
  configurationFlag: false,
  customizedProductCategory: '0',
  minOrderQuantity: 1,
  maxOrderQuantity: 100,
  stepQuantity: 1,
  storeMinOrderQuantity: 1,
  storeMaxOrderQuantity: 100,
  storeStepOrderQuantity: 1,
  newPeriodFrom: '2023-05-24T02:00:10.000Z',
  reserveFromStoreDisabled: false,
  sendToStoreDisabled: false,
  personalDeliveryDisabled: false,
  estimatedArrivalDays: 3,
  productWithServiceFlag: false,
  dropShippingCategory: '1',
  largeSizedProductCategoryEc: '0',
  originCountryCode: 'JP',
  flavorExpirationCategory: '0',
  flavorExpiration: 3,
  productCharacteristics:
    'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
  colorPattern: '黒',
  size: '',
  brandName: '',
  singleItemSizeWidth: 19.1,
  singleItemSizeHeight: 5.1,
  singleItemSizeDepth: 7.7,
  contentAmount: 10,
  contentAmountUnit: 'L',
  modelNo: '',
  lawsStandards: 'JIS',
  singleItemSize2Width: 19.1,
  singleItemSize2Height: 5.1,
  singleItemSize2Depth: 7.7,
  specCategory: [
    {
      name: 'カラー',
      value: '',
    },
    {
      name: '本体サイズ-幅(cm)',
      value: '19',
    },
    {
      name: '本体サイズ-奥行(cm)',
      value: '14.5',
    },
  ],
  characterCopyrightNameEc: '',
  longDescription:
    "<p class='m-bold'>大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ!</p>\\\\r\\\\n\\\\r\\\\n<ul class='m-listDot'>\\\\r\\\\n  <li>固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。</li>\\\\r\\\\n  <li>おからが主原料なので燃やすことができます。</li>\\\\r\\\\n  <li>生ごみとしても処理できます。</li>\\\\r\\\\n  <li>消臭</li>\\\\r\\\\n</ul>\\\\r\\\\n\\\\r\\\\n",
  cautions: '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
  productSpecGroupId: '',
  similarProduct: '',
  recommendedProduct: '',
  comparativeProduct: '',
  kukuru: '00000152',
  variation: [
    {
      name: '01-001',
      value: '4',
    },
    {
      name: '01-001',
      value: '4',
    },
  ],
  faceProductId: '00000152',
  serviceContents: '',
  prices: [
    {
      productId: '4549509646945',
      storeCode: '859',
      membershipRank: '4',
      priceIncludingTax: 8980,
      salePriceIncludingTax: 7980,
    },
    {
      productId: '4549509646945',
      storeCode: '888',
      membershipRank: '4',
      priceIncludingTax: 8980,
      salePriceIncludingTax: 7980,
    },
  ],
  inventories: [
    {
      productId: '4549509646952',
      storeCode: '859',
      quantityOpening: 10,
      quantitySold: 3,
      quantityAvailable: 6,
      quantityAllocated: 1,
      quantityExpected: 3,
      expectedArrivalDate: '2023-03-03T00:00:00.000Z',
    },
    {
      productId: '4549509646952',
      storeCode: '123',
      quantityOpening: 10,
      quantitySold: 3,
      quantityAvailable: 6,
      quantityAllocated: 1,
      quantityExpected: 3,
    },
  ],
  createdBy: '',
  createdAt: '',
  updatedBy: '',
  updatedAt: '',
};
const memberData = {
  lastName: '山田',
  firstName: '太郎',
  lastNameKana: 'ヤマダ',
  firstNameKana: 'タロウ',
  phoneNumber: '495251000',
  postCode: '3670030',
  prefectures: '埼玉県',
  city: '本庄市',
  address1: '早稲田の杜一丁目2番1号',
  address2: 'カインズマンション100号室',
  memberId: '123456789012',
};
const addressBookData = [
  {
    id: '123456789012',
    name: '667321550',
    accountId: '123456789012',
    isFavorite: true,
    title: 'アドレス帳データのタイトル',
    firstName: '太郎',
    lastName: '埼玉',
    firstNameKana: 'タロウ',
    ownNameKana: 'サイタマ',
    zipCode: '3671234',
    prefecture: '埼玉県',
    address1: '早稲田の杜一丁目９９番９９９号',
    address2: 'カインズビル',
    address3: '早稲田の杜一丁目９９番９９９号',
    phone: '0120999999',
    phone2: '0120971952',
    email: 'Taro@test.co.jp',
    companyName: '株式会社　ECリプレイス',
    departmentName: '情報システム部',
    memo: 'アドレス帳データメモ',
    ownerId: '591158720',
    createdBy: '491156721',
    createdAt: '2023-06-23 09:07',
    lastModifiedBy: '491156721',
    lastModifiedAt: '2023-06-23 12:07',
  },
];
const myStoresData = [
  {
    code: '813',
    name: 'カインズ本庄早稲田店',
    address: '埼玉県本庄市早稲田の杜二丁目１番１号',
    businessTime: '9:00〜20:00',
    isFavoriteStore: true,
    originalCreatedAt: '2023-07-24T02:00:10.000Z',
  },
  {
    code: '859',
    name: 'カインズ朝霞店',
    address: '埼玉県朝霞市根岸台３丁目２０−１',
    businessTime: '9:00〜20:00',
    isFavoriteStore: false,
    originalCreatedAt: '2023-09-24T02:32:10.000Z',
  },
];
const productItems = [
  {
    itemId: '48677635-ac6a-4412-8f68-5a933a166a29',
    receivingMethod: '1',
    productId: '4549509524318',
    quantity: 20,
    orderSpecification: {
      simulationNumber: '980089',
      height: 90,
      width: 200,
      hook: 'A',
    },
    product: {
      productId: '4549509524318',
      name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
      categoryId: 'c2320',
      imageUrls: [
        'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
        'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
        'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
      ],
      departmentCode: '014',
      lineCode: '221',
      classCode: '1400',
      description: '',
      applicableStartDate: '2023-05-24T02:00:10.000Z',
      salesStartDate: '2023-05-24T02:00:10.000Z',
      consumptionTaxRate: 10,
      consumptionTaxCategory: '',
      salesEndDate: '2023-05-24T02:00:10.000Z',
      salesEndFlag: false,
      designatedPharmaceuticalCategory: '0',
      liquorCategory: '0',
      tobaccoCategory: '0',
      hazardousMaterialFlag: false,
      medicalEquipmentClass: '',
      poisonousDeleteriousSubstanceCategory: '0',
      poisonousDrugCategory: '0',
      agriculturalChemicalCategory: '0',
      animalDrugCategory: '0',
      warrantyIssuanceCategory: '0',
      pharmaceuticalFlag: false,
      salesTypeCategory: '0',
      warrantyCategory: '0',
      warrantyPeriod: '1年間',
      deliveryChargeCategoryEc: '1',
      onlineFlagEc: true,
      onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
      onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
      consumptionTaxCategoryEc: '0',
      onlineSalesCategoryEc: '0',
      individualDeliveryChargeEc: 600,
      setProductFlag: false,
      configurationFlag: false,
      customizedProductCategory: '0',
      minOrderQuantity: 1,
      maxOrderQuantity: 100,
      stepQuantity: 1,
      storeMinOrderQuantity: 1,
      storeMaxOrderQuantity: 100,
      storeStepOrderQuantity: 1,
      newPeriodFrom: '2023-05-24T02:00:10.000Z',
      reserveFromStoreDisabled: false,
      sendToStoreDisabled: false,
      personalDeliveryDisabled: false,
      estimatedArrivalDays: 3,
      productWithServiceFlag: false,
      dropShippingCategory: '0',
      largeSizedProductCategoryEc: '0',
      originCountryCode: 'JP',
      flavorExpirationCategory: '0',
      flavorExpiration: 3,
      productCharacteristics:
        'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
      colorPattern: '黒',
      size: '',
      brandName: '',
      singleItemSizeWidth: 19.1,
      singleItemSizeHeight: 5.1,
      singleItemSizeDepth: 7.7,
      contentAmount: 10,
      contentAmountUnit: 'L',
      modelNo: '',
      lawsStandards: 'JIS',
      singleItemSize2Width: 19.1,
      singleItemSize2Height: 5.1,
      singleItemSize2Depth: 7.7,
      specCategory: [
        {
          name: 'カラー',
          value: '',
        },
        {
          name: '本体サイズ-幅(cm)',
          value: '19',
        },
        {
          name: '本体サイズ-奥行(cm)',
          value: '14.5',
        },
      ],
      characterCopyrightNameEc: '',
      longDescription:
        "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
      cautions:
        '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
      productSpecGroupId: '',
      similarProduct: '',
      recommendedProduct: '',
      comparativeProduct: '',
      kukuru: '00000152',
      variation: [
        {
          name: '01-001',
          value: '4',
        },
        {
          name: '01-001',
          value: '4',
        },
      ],
      faceProductId: '00000152',
      serviceContents: '',
      prices: [
        {
          productId: '4549509524318',
          storeCode: '859',
          membershipRank: '4',
          priceIncludingTax: 8980,
          salePriceIncludingTax: 7980,
        },
        {
          productId: '4549509524318',
          storeCode: '123',
          membershipRank: '4',
          priceIncludingTax: 8980,
          salePriceIncludingTax: 7980,
        },
      ],
      inventories: [
        {
          productId: '4549509524318',
          storeCode: '859',
          quantityOpening: 10,
          quantitySold: 3,
          quantityAvailable: 6,
          quantityAllocated: 1,
          quantityExpected: 3,
          expectedArrivalDate: '2023-03-03T00:00:00.000Z',
        },
        {
          productId: '4549509524318',
          storeCode: '123',
          quantityOpening: 10,
          quantitySold: 3,
          quantityAvailable: 6,
          quantityAllocated: 1,
          quantityExpected: 3,
        },
      ],
      createdBy: '',
      createdAt: '',
      updatedBy: '',
      updatedAt: '',
    },
    delivery: {
      shipping: {
        estimatedDate: '2023-06-23',
        canSelectDate: false,
        items: [
          {
            productCode: '4549509524318',
            estimatedDate: '2023-06-23',
            isSeparate: false,
          },
        ],
      },
      pickup: {
        dateTime: '2023-06-23 09:07',
        items: [
          {
            productCode: '4549509524318',
            estimatedDate: '2023-06-23',
            isSeparate: false,
          },
        ],
      },
    },
    setProductType: '0',
    isReserveFromStoreAvailable: true,
    isPersonalDeliveryAvailable: true,
    invalidWebBackOrderFlagForStorePickup: false,
    invalidWebBackOrderFlagForDesignatedDelivery: true,
    isWebBackOrder: false,
    unitPrice: 2000,
    subtotalProductAmount: 10000,
    individualShippingCost: 4000,
    subtotalIndividualShippingCost: 3200,
    campaignPoints: 1800,
    subtotalCampaignPoints: 3600,
    isCheckoutTarget: false,
    checkoutId: '123456',
    checkoutStatus: 'Completed',
    errors: [
      {
        category: 'detail1',
        errorCode: 'carts-line-error-001',
        description:
          '同時購入できない商品があります。商品を削除するか、それ以外の商品を削除してください。',
      },
    ],
    notifications: [
      {
        messageCode: '...',
        description: '...,',
      },
    ],
    createdAt: '2023-11-14T13:40:20+07:21',
    updatedAt: '2023-11-15T13:40:21+09:00',
  },
  {
    itemId: '87092821394372',
    receivingMethod: '1',
    productId: '4549509524317',
    quantity: 20,
    orderSpecification: {
      simulationNumber: '980089',
      height: 90,
      width: 200,
      hook: 'A',
    },
    product: {
      productId: '4549509524317',
      name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
      categoryId: 'c2320',
      imageUrls: [
        'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
        'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
        'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
      ],
      departmentCode: '014',
      lineCode: '221',
      classCode: '1400',
      description: '',
      applicableStartDate: '2023-05-24T02:00:10.000Z',
      salesStartDate: '2023-05-24T02:00:10.000Z',
      consumptionTaxRate: 10,
      consumptionTaxCategory: '',
      salesEndDate: '2023-05-24T02:00:10.000Z',
      salesEndFlag: false,
      designatedPharmaceuticalCategory: '0',
      liquorCategory: '0',
      tobaccoCategory: '0',
      hazardousMaterialFlag: false,
      medicalEquipmentClass: '',
      poisonousDeleteriousSubstanceCategory: '0',
      poisonousDrugCategory: '0',
      agriculturalChemicalCategory: '0',
      animalDrugCategory: '0',
      warrantyIssuanceCategory: '0',
      pharmaceuticalFlag: false,
      salesTypeCategory: '0',
      warrantyCategory: '0',
      warrantyPeriod: '1年間',
      deliveryChargeCategoryEc: '1',
      onlineFlagEc: true,
      onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
      onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
      consumptionTaxCategoryEc: '0',
      onlineSalesCategoryEc: '0',
      individualDeliveryChargeEc: 600,
      setProductFlag: false,
      configurationFlag: false,
      customizedProductCategory: '0',
      minOrderQuantity: 1,
      maxOrderQuantity: 100,
      stepQuantity: 1,
      storeMinOrderQuantity: 1,
      storeMaxOrderQuantity: 100,
      storeStepOrderQuantity: 1,
      newPeriodFrom: '2023-05-24T02:00:10.000Z',
      reserveFromStoreDisabled: false,
      sendToStoreDisabled: false,
      personalDeliveryDisabled: false,
      estimatedArrivalDays: 3,
      productWithServiceFlag: false,
      dropShippingCategory: '0',
      largeSizedProductCategoryEc: '0',
      originCountryCode: 'JP',
      flavorExpirationCategory: '0',
      flavorExpiration: 3,
      productCharacteristics:
        'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
      colorPattern: '黒',
      size: '',
      brandName: '',
      singleItemSizeWidth: 19.1,
      singleItemSizeHeight: 5.1,
      singleItemSizeDepth: 7.7,
      contentAmount: 10,
      contentAmountUnit: 'L',
      modelNo: '',
      lawsStandards: 'JIS',
      singleItemSize2Width: 19.1,
      singleItemSize2Height: 5.1,
      singleItemSize2Depth: 7.7,
      specCategory: [
        {
          name: 'カラー',
          value: '',
        },
        {
          name: '本体サイズ-幅(cm)',
          value: '19',
        },
        {
          name: '本体サイズ-奥行(cm)',
          value: '14.5',
        },
      ],
      characterCopyrightNameEc: '',
      longDescription:
        "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます",
      cautions:
        '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
      productSpecGroupId: '',
      similarProduct: '',
      recommendedProduct: '',
      comparativeProduct: '',
      kukuru: '00000152',
      variation: [
        {
          name: '01-001',
          value: '4',
        },
        {
          name: '01-001',
          value: '4',
        },
      ],
      faceProductId: '00000152',
      serviceContents: '',
      prices: [
        {
          productId: '4549509524317',
          storeCode: '859',
          membershipRank: '4',
          priceIncludingTax: 8980,
          salePriceIncludingTax: 7980,
        },
        {
          productId: '4549509524317',
          storeCode: '123',
          membershipRank: '4',
          priceIncludingTax: 8980,
          salePriceIncludingTax: 7980,
        },
      ],
      inventories: [
        {
          productId: '4549509524317',
          storeCode: '859',
          quantityOpening: 10,
          quantitySold: 3,
          quantityAvailable: 6,
          quantityAllocated: 1,
          quantityExpected: 3,
          expectedArrivalDate: '2023-03-03T00:00:00.000Z',
        },
        {
          productId: '4549509524317',
          storeCode: '123',
          quantityOpening: 10,
          quantitySold: 3,
          quantityAvailable: 6,
          quantityAllocated: 1,
          quantityExpected: 3,
        },
      ],
      createdBy: '',
      createdAt: '',
      updatedBy: '',
      updatedAt: '',
    },
    delivery: {
      shipping: {
        estimatedDate: '2023-06-23',
        canSelectDate: false,
        items: [
          {
            productCode: '4549509524317',
            estimatedDate: '2023-06-23',
            isSeparate: false,
          },
        ],
      },
      pickup: {
        dateTime: '2023-06-23 09:08',
        items: [
          {
            productCode: '4549509524317',
            estimatedDate: '2023-06-23',
            isSeparate: false,
          },
        ],
      },
    },
    setProductType: '0',
    isReserveFromStoreAvailable: true,
    isPersonalDeliveryAvailable: true,
    invalidWebBackOrderFlagForStorePickup: false,
    invalidWebBackOrderFlagForDesignatedDelivery: true,
    isWebBackOrder: false,
    unitPrice: 2000,
    subtotalProductAmount: 10000,
    individualShippingCost: 4000,
    subtotalIndividualShippingCost: 3200,
    campaignPoints: 1800,
    subtotalCampaignPoints: 3600,
    isCheckoutTarget: false,
    checkoutId: '123456',
    checkoutStatus: 'In-progress',
    errors: [
      {
        category: 'detail1',
        errorCode: 'carts-line-error-001',
        description:
          '同時購入できない商品があります。商品を削除するか、それ以外の商品を削除してください。',
      },
    ],
    notifications: [
      {
        messageCode: '...',
        description: '...,',
      },
    ],
    createdAt: '2023-11-14T13:40:21+09:00',
    updatedAt: '2023-11-15T13:40:21+09:00',
  },
];
const products = [
  {
    productId: '4549509646952',
    name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
    categoryId: 'c2320',
    imageUrls: [
      'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
    ],
    departmentCode: '014',
    lineCode: '221',
    classCode: '1400',
    description: '',
    applicableStartDate: '2023-05-24T02:00:10.000Z',
    salesStartDate: '2023-05-24T02:00:10.000Z',
    consumptionTaxRate: 10,
    consumptionTaxCategory: '',
    salesEndDate: '2023-05-24T02:00:10.000Z',
    salesEndFlag: false,
    designatedPharmaceuticalCategory: '0',
    liquorCategory: '0',
    tobaccoCategory: '0',
    hazardousMaterialFlag: false,
    medicalEquipmentClass: '',
    poisonousDeleteriousSubstanceCategory: '0',
    poisonousDrugCategory: '0',
    agriculturalChemicalCategory: '0',
    animalDrugCategory: '0',
    warrantyIssuanceCategory: '0',
    pharmaceuticalFlag: false,
    salesTypeCategory: '0',
    warrantyCategory: '0',
    warrantyPeriod: '1年間',
    deliveryChargeCategoryEc: '1',
    onlineFlagEc: true,
    onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
    onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
    consumptionTaxCategoryEc: '0',
    onlineSalesCategoryEc: '0',
    individualDeliveryChargeEc: 600,
    setProductFlag: false,
    configurationFlag: false,
    customizedProductCategory: '0',
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    stepQuantity: 1,
    storeMinOrderQuantity: 1,
    storeMaxOrderQuantity: 100,
    storeStepOrderQuantity: 1,
    newPeriodFrom: '2023-05-24T02:00:10.000Z',
    reserveFromStoreDisabled: false,
    sendToStoreDisabled: false,
    personalDeliveryDisabled: false,
    estimatedArrivalDays: 3,
    productWithServiceFlag: false,
    dropShippingCategory: '0',
    largeSizedProductCategoryEc: '0',
    originCountryCode: 'JP',
    flavorExpirationCategory: '0',
    flavorExpiration: 3,
    productCharacteristics:
      'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
    colorPattern: '黒',
    size: '',
    brandName: '',
    singleItemSizeWidth: 19.1,
    singleItemSizeHeight: 5.1,
    singleItemSizeDepth: 7.7,
    contentAmount: 10,
    contentAmountUnit: 'L',
    modelNo: '',
    lawsStandards: 'JIS',
    singleItemSize2Width: 19.1,
    singleItemSize2Height: 5.1,
    singleItemSize2Depth: 7.7,
    specCategory: [
      {
        name: 'カラー',
        value: '',
      },
      {
        name: '本体サイズ-幅(cm)',
        value: '19',
      },
      {
        name: '本体サイズ-奥行(cm)',
        value: '14.5',
      },
    ],
    characterCopyrightNameEc: '',
    longDescription:
      "<p class='m-bold'>大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ!</p>\\\\r\\\\n\\\\r\\\\n<ul class='m-listDot'>\\\\r\\\\n  <li>固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。</li>\\\\r\\\\n  <li>おからが主原料なので燃やすことができます。</li>\\\\r\\\\n  <li>生ごみとしても処理できます。</li>\\\\r\\\\n  <li>消臭</li>\\\\r\\\\n</ul>\\\\r\\\\n\\\\r\\\\n",
    cautions: '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
    productSpecGroupId: '',
    similarProduct: '',
    recommendedProduct: '',
    comparativeProduct: '',
    kukuru: '00000152',
    variation: [
      {
        name: '01-001',
        value: '4',
      },
      {
        name: '01-001',
        value: '4',
      },
    ],
    faceProductId: '00000152',
    serviceContents: '',
    prices: [
      {
        productId: '4549509646945',
        storeCodes: '859',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
      {
        productId: '4549509646945',
        storeCodes: '123',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
    ],
    inventories: [
      {
        productId: '4549509646952',
        storeCode: '859',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
        expectedArrivalDate: '2023-03-03T00:00:00.000Z',
      },
      {
        productId: '4549509646952',
        storeCode: '123',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
      },
    ],
    createdBy: '',
    createdAt: '',
    updatedBy: '',
    updatedAt: '',
  },
  {
    productId: '4549509646952',
    name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
    categoryId: 'c2320',
    imageUrls: [
      'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
    ],
    departmentCode: '014',
    lineCode: '221',
    classCode: '1400',
    description: '',
    applicableStartDate: '2023-05-24T02:00:10.000Z',
    salesStartDate: '2023-05-24T02:00:10.000Z',
    consumptionTaxRate: 10,
    consumptionTaxCategory: '',
    salesEndDate: '2023-05-24T02:00:10.000Z',
    salesEndFlag: false,
    designatedPharmaceuticalCategory: '0',
    liquorCategory: '0',
    tobaccoCategory: '0',
    hazardousMaterialFlag: false,
    medicalEquipmentClass: '',
    poisonousDeleteriousSubstanceCategory: '0',
    poisonousDrugCategory: '0',
    agriculturalChemicalCategory: '0',
    animalDrugCategory: '0',
    warrantyIssuanceCategory: '0',
    pharmaceuticalFlag: false,
    salesTypeCategory: '0',
    warrantyCategory: '0',
    warrantyPeriod: '1年間',
    deliveryChargeCategoryEc: '1',
    onlineFlagEc: true,
    onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
    onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
    consumptionTaxCategoryEc: '0',
    onlineSalesCategoryEc: '0',
    individualDeliveryChargeEc: 600,
    setProductFlag: false,
    configurationFlag: false,
    customizedProductCategory: '0',
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    stepQuantity: 1,
    storeMinOrderQuantity: 1,
    storeMaxOrderQuantity: 100,
    storeStepOrderQuantity: 1,
    newPeriodFrom: '2023-05-24T02:00:10.000Z',
    reserveFromStoreDisabled: false,
    sendToStoreDisabled: false,
    personalDeliveryDisabled: false,
    estimatedArrivalDays: 3,
    productWithServiceFlag: false,
    dropShippingCategory: '0',
    originCountryCode: 'JP',
    flavorExpirationCategory: '0',
    flavorExpiration: 3,
    productCharacteristics:
      'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
    colorPattern: '黒',
    size: '',
    brandName: '',
    singleItemSizeWidth: 19.1,
    singleItemSizeHeight: 5.1,
    singleItemSizeDepth: 7.7,
    contentAmount: 10,
    contentAmountUnit: 'L',
    modelNo: '',
    lawsStandards: 'JIS',
    singleItemSize2Width: 19.1,
    singleItemSize2Height: 5.1,
    singleItemSize2Depth: 7.7,
    specCategory: [
      {
        name: 'カラー',
        value: '',
      },
      {
        name: '本体サイズ-幅(cm)',
        value: '19',
      },
      {
        name: '本体サイズ-奥行(cm)',
        value: '14.5',
      },
    ],
    characterCopyrightNameEc: '',
    longDescription:
      "<p class='m-bold'>大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ!</p>\\\\r\\\\n\\\\r\\\\n<ul class='m-listDot'>\\\\r\\\\n  <li>固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。</li>\\\\r\\\\n  <li>おからが主原料なので燃やすことができます。</li>\\\\r\\\\n  <li>生ごみとしても処理できます。</li>\\\\r\\\\n  <li>消臭</li>\\\\r\\\\n</ul>\\\\r\\\\n\\\\r\\\\n",
    cautions: '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
    productSpecGroupId: '',
    similarProduct: '',
    recommendedProduct: '',
    comparativeProduct: '',
    kukuru: '00000152',
    variation: [
      {
        name: '01-001',
        value: '4',
      },
      {
        name: '01-001',
        value: '4',
      },
    ],
    faceProductId: '00000152',
    serviceContents: '',
    prices: [
      {
        productId: '4549509646945',
        storeCodes: '859',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
      {
        productId: '4549509646945',
        storeCodes: '123',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
    ],
    inventories: [
      {
        productId: '4549509646952',
        storeCode: '859',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
        expectedArrivalDate: '2023-03-03T00:00:00.000Z',
      },
      {
        productId: '4549509646952',
        storeCode: '123',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
      },
    ],
    createdBy: '',
    createdAt: '',
    updatedBy: '',
    updatedAt: '',
  },
];
const storeInfo = {
  code: '859',
  name: 'カインズ本庄早稲田店',
  webUrl: 'https://map.cainz.com/detail/859/',
  address: '〒351-0005 埼玉県朝霞市根岸台3丁目20番1号',
  postCode: '351-0005',
  telNumberList: [
    {
      contactName: '本館',
      telNumber: '048-468-0111',
    },
  ],
  businessTime: '9:00〜20:00',
  businessTimeNote: '本館以外は19:00閉店',
  regularHoliday: '1月1日',
  regularHolidayNote: 'その他不定休あり',
  webOpenStoreFlag: true,
  detail: {
    code: '813',
    landscape: {
      latitude: 35.808684,
      longitude: 139.610384,
    },
    floorGuideList: [
      {
        floorGuideOrder: 1,
        floorGuideName: '本館',
        floorGuidePdfUrl:
          'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FPDF%2F859_1_%E6%9C%AC%E9%A4%A8.pdf?alt=media',
        floorGuideUrl:
          'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FJPG%2F859_1_%E6%9C%AC%E9%A4%A8.jpg?alt=media',
      },
    ],
    prefectureName: '埼玉県',
    prefectureCode: '11',
    regionCode: '03',
    regionName: '関東地方',
    openingDate: '2020-09-23T00:00:00Z',
    closingDate: '9999-12-31T00:00:00Z',
    closedMessage: '閉店',
    supportPickup: true,
    supportCredit: true,
    supportPickupInnerLocker: true,
    supportPickupPlace: true,
    supportPickupPlaceParking: true,
    supportBackOrder: true,
    supportGeomagnetism: true,
    geomagnetismMapId: 'b8e3ef31b120404b848aa9fe1f66fc5a',
    supportPocketRegi: true,
    supportCuttingService: false,
    webCuttingServiceUrl: 'https://www.cainz.co.jp/store_cutting/813',
    supportDIYReserve: true,
    webDIYReserveUrl: 'https://reserve.cainz.com/store/813',
    supportDogRun: true,
    webDogRunUrl: 'https://dogrun.cainz.com/',
    supportToolRental: true,
    webToolRentalUrl: 'https://reserve.cainz.com/store/813/',
    showVisitingNumber: 0,
    toCloseSettings: [
      {
        toCloseType: 'message',
        toCloseFrom: '2021-12-29T20:00:00Z',
        toCloseUntil: '2022-01-03T20:00:00Z',
        toCloseMessage:
          '年末年始の営業時間は下記の店舗詳細WEBページからご確認ください。',
      },
    ],
    storeAreaCode: '09',
    storeAreaName: '埼玉第1エリア',
    searchWords: 'あさかｱｻｶアサカ',
    digitalFlyerURL: 'https://www.shufoo.net/pntweb/shopDetail/235839/',
    materialHallExistence: true,
    cultureClassExistence: false,
    cycleParkExistence: true,
    DIYSTYLEFloorExistence: true,
    dogParkExistence: true,
    exteriorPlazaExistence: true,
    foodAreaExistence: false,
    gardeningHallExistence: false,
    greenAdvisorExistence: false,
    petsOneExistence: true,
    reformCenterExistence: true,
    workshopExistence: false,
    storePickupExistence: true,
    supermarketExistence: true,
  },
  announcements: [
    {
      code: '813',
      title: '写真プリントキャンペーン',
      body: "開催日：2023年5月15日～2023年6月19日\rイベント内容：\r昔撮った思い出のビデオテープ …時が経つにつれテープの劣化やハード機器の故障等で観たいときに観れなくなるかもしれません。この機会に大切な動画をDVDに、音楽等をCDにダビングしてみませんか？\r2023年5月15日より2023年6月19日までの期間中、テープ5本以上のご注文で1本980円（税込）でお受け致します。（通常：10本以上のご注文で1本980円）各店サービスカウンターにて承りますので是非ご利用願います。\r問い合わせ先：サービスカウンター受付\r\r<b>くみまちモールあさか</b>\rカインズとイトーヨーカドーと30の専門店がスマートなくらしを応援します。\r<a href='https://cainz-kumimachi-asaka.com/' target='_blank'>詳細はこちら</a>",
    },
  ],
};
const bffProductItem = {
  itemId: 'MlgzTxGMz9XWS4J81ZH0',
  receivingMethod: '2',
  productId: '4905620219350',
  quantity: 10,
  orderSpecification: {
    simulationNumber: '01-12-123456',
    height: 200,
    width: 200,
    hook: 'A',
  },
  product: bffProductData,
  delivery: {
    shipping: {
      estimatedDate: '2023-06-23',
      canSelectDate: false,
      items: [
        {
          productCode: '4549509524318',
          estimatedDate: '2023-06-23',
          isSeparate: false,
        },
      ],
    },
    pickup: {
      dateTime: '2023-06-23 09:07',
      items: [
        {
          productCode: '4549509524318',
          estimatedDate: '2023-06-23',
          isSeparate: false,
        },
      ],
    },
  },
  setProductType: '0',
  isReserveFromStoreAvailable: true,
  isPersonalDeliveryAvailable: true,
  invalidWebBackOrderFlagForStorePickup: false,
  invalidWebBackOrderFlagForDesignatedDelivery: false,
  isWebBackOrder: false,
  unitPrice: 198,
  subtotalProductAmount: 1980,
  individualShippingCost: 0,
  subtotalIndividualShippingCost: 0,
  campaignPoints: 0,
  subtotalCampaignPoints: 0,
  isCheckoutTarget: true,
  checkoutId: '',
  checkoutStatus: '',
  errors: [
    {
      category: 'detail1',
      errorCode: 'carts-line-error-001',
      description:
        '同時購入できない商品があります。商品を削除するか、それ以外の商品を削除してください。',
    },
  ],
  notifications: [
    {
      messageCode: '...',
      description: '...,',
    },
  ],
  createdAt: '2023-11-16T02:00:10.000Z',
  updatedAt: '2023-11-16T02:00:10.000Z',
};
const userInfo = {
  isMember: true,
  billPayment: true,
  zipCode: '3670030',
  prefecture: '埼玉県',
};
const getCartData = {
  productItems: [
    {
      itemId: '48677635-ac6a-4412-8f68-5a933a166a29',
      receivingMethod: '1',
      productId: '4549509524318',
      quantity: 20,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4549509524318',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 10,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: true,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: false,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '0',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.1,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4549509524318',
            storeCodes: '859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4549509524318',
            storeCodes: '123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4549509524318',
            storeCode: '859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4549509524317',
            storeCode: '123',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:07',
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: false,
      checkoutId: '123456',
      checkoutStatus: 'Completed',
      errors: null,
      notifications: null,
      createdAt: '2023-11-14T13:40:20+07:21',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
  ],
  storeInfo: {
    code: '859',
    name: 'カインズ本庄早稲田店',
    webUrl: 'https://map.cainz.com/detail/859/',
    address: '〒351-0005 埼玉県朝霞市根岸台3丁目20番1号',
    postCode: '351-0005',
    telNumberList: [
      {
        contactName: '本館',
        telNumber: '048-468-0111',
      },
    ],
    businessTime: '9:00〜20:00',
    businessTimeNote: '本館以外は19:00閉店',
    regularHoliday: '1月1日',
    regularHolidayNote: 'その他不定休あり',
    webOpenStoreFlag: true,
    detail: {
      code: '813',
      landscape: {
        latitude: 35.808684,
        longitude: 139.610384,
      },
      floorGuideList: [
        {
          floorGuideOrder: 1,
          floorGuideName: '本館',
          floorGuidePdfUrl:
            'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FPDF%2F859_1_%E6%9C%AC%E9%A4%A8.pdf?alt=media',
          floorGuideUrl:
            'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FJPG%2F859_1_%E6%9C%AC%E9%A4%A8.jpg?alt=media',
        },
      ],
      prefectureName: '埼玉県',
      prefectureCode: '11',
      regionCode: '03',
      regionName: '関東地方',
      openingDate: '2020-09-23T00:00:00Z',
      closingDate: '9999-12-31T00:00:00Z',
      closedMessage: '閉店',
      supportPickup: true,
      supportCredit: true,
      supportPickupInnerLocker: true,
      supportPickupPlace: true,
      supportPickupPlaceParking: true,
      supportBackOrder: true,
      supportGeomagnetism: true,
      geomagnetismMapId: 'b8e3ef31b120404b848aa9fe1f66fc5a',
      supportPocketRegi: true,
      supportCuttingService: false,
      webCuttingServiceUrl: 'https://www.cainz.co.jp/store_cutting/813',
      supportDIYReserve: true,
      webDIYReserveUrl: 'https://reserve.cainz.com/store/813',
      supportDogRun: true,
      webDogRunUrl: 'https://dogrun.cainz.com/',
      supportToolRental: true,
      webToolRentalUrl: 'https://reserve.cainz.com/store/813/',
      showVisitingNumber: 0,
      toCloseSettings: [
        {
          toCloseType: 'message',
          toCloseFrom: '2021-12-29T20:00:00Z',
          toCloseUntil: '2022-01-03T20:00:00Z',
          toCloseMessage:
            '年末年始の営業時間は下記の店舗詳細WEBページからご確認ください。',
        },
      ],
      storeAreaCode: '09',
      storeAreaName: '埼玉第1エリア',
      searchWords: 'あさかｱｻｶアサカ',
      digitalFlyerURL: 'https://www.shufoo.net/pntweb/shopDetail/235839/',
      materialHallExistence: true,
      cultureClassExistence: false,
      cycleParkExistence: true,
      DIYSTYLEFloorExistence: true,
      dogParkExistence: true,
      exteriorPlazaExistence: true,
      foodAreaExistence: false,
      gardeningHallExistence: false,
      greenAdvisorExistence: false,
      petsOneExistence: true,
      reformCenterExistence: true,
      workshopExistence: false,
      storePickupExistence: true,
      supermarketExistence: true,
    },
    announcements: [
      {
        code: '813',
        title: '写真プリントキャンペーン',
        body: "開催日：2023年5月15日～2023年6月19日\rイベント内容：\r昔撮った思い出のビデオテープ …時が経つにつれテープの劣化やハード機器の故障等で観たいときに観れなくなるかもしれません。この機会に大切な動画をDVDに、音楽等をCDにダビングしてみませんか？\r2023年5月15日より2023年6月19日までの期間中、テープ5本以上のご注文で1本980円（税込）でお受け致します。（通常：10本以上のご注文で1本980円）各店サービスカウンターにて承りますので是非ご利用願います。\r問い合わせ先：サービスカウンター受付\r\r<b>くみまちモールあさか</b>\rカインズとイトーヨーカドーと30の専門店がスマートなくらしを応援します。\r<a href='https://cainz-kumimachi-asaka.com/' target='_blank'>詳細はこちら</a>",
      },
    ],
  },
  estimatedPickupableDateTime: '2023-11-01 09:00',
  shippingAddress: {
    postalCode: '3670012',
    prefecture: '埼玉県',
    city: '本庄市',
  },
  amountInfo: {
    totalProductAmount: 12345,
    basicShippingCost: 9000,
    regionalShippingCost: 7000,
    totalIndividualShippingCost: 1200,
    totalGrossAmount: 20000,
    priceToFreeBasicShipping: 32000,
  },
  storeItemCount: 2,
  shippingItemCount: 2,
  amazonPayButtonConfig: {
    sandbox: false,
    merchantId: '1234',
    ledgerCurrency: '円',
    checkoutLanguage: '日本語',
    productType: '1',
    placement: '1',
    buttonColor: 'ライトグレー',
    estimatedOrderAmount: {
      amount: 1000,
      currency_code: 'JPY',
    },
    createCheckoutSessionConfig: {
      payloadJSON: 'a@er4578',
      signature: '0qwe0987fty6523',
      publicKeyId: 'a1234@#890',
      algorithm: 'SHA-224',
    },
  },
};
const checkNonDeliveryData = {
  productItems: [
    {
      itemId: '17392851394179',
      receivingMethod: '1',
      productId: '4549509524318',
      quantity: 4,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4549509524318',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 15,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: false,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-11-30T09:24:47.354Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: true,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '3',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.01,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4549509524318',
            storeCodes: '0859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4549509524318',
            storeCodes: '0123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4549509524318',
            storeCode: '0859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4549509524318',
            storeCode: '0876',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: true,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:07',
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: true,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: true,
      checkoutId: '123456',
      checkoutStatus: 'Completed',
      createdAt: '2023-11-14T13:40:20+07:21',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
  ],
  deliveryInfo: {
    zipCode: '1001000',
    prefecture: '東京都',
    city: '新宿区',
    address1: 'テスト',
  },
};

const bffCreditCardData = [
  {
    cardSequentialNumber: '123',
    cardNumber: '***********184',
    expirationDate: '12/23',
    isDeleted: true,
    isDefault: true,
  },
];

const cartInUse = 'users/GyyDoynLuce4qWcm9cj4/carts/SIwU1ZX6nIxTL7x3AYRW';
const updateProductItems = [
  {
    itemId: '17392851394179',
    receivingMethod: '2',
    productId: '4549509524318',
    quantity: 4,
    setProductType: '0',
    product: null,
    isReserveFromStoreAvailable: true,
    isPersonalDeliveryAvailable: true,
    invalidWebBackOrderFlagForStorePickup: false,
    invalidWebBackOrderFlagForDesignatedDelivery: true,
    isWebBackOrder: false,
    unitPriceForStorePickup: 2000,
    unitPriceForDelivery: 1000,
    selectedUnitPrice: 1000,
    unitPrice: 2000,
    subtotalProductAmount: 10000,
    individualShippingCost: 4000,
    subtotalIndividualShippingCost: 3200,
    campaignPoints: 1800,
    subtotalCampaignPoints: 3600,
    isCheckoutTarget: true,
    checkoutId: '123456',
    checkoutStatus: 'Completed',
    createdAt: '2023-11-14T13:40:20+07:21',
    updatedAt: '2023-11-15T13:40:21+09:00',
  },
];
const shippingAddress = {
  zipCode: '1001022',
  prefecture: '東京都',
  city: '新宿区',
  addressBookId: '3456',
};
export {
  bffStoreData,
  bffProductData,
  bffProductItem,
  memberData,
  addressBookData,
  myStoresData,
  productItems,
  products,
  storeInfo,
  userInfo,
  getCartData,
  checkNonDeliveryData,
  bffCreditCardData,
  cartInUse,
  updateProductItems,
  shippingAddress,
};
