steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-f',
        '$_DOCKER_FILE',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
        '--build-arg',
        'SERVICE_NAME=${_SERVICE_NAME}',
        '--build-arg',
        'ENV_CONFIG_FILE_NAME=${_ENV_CONFIG_FILE_NAME}',
        '.',
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
      ]
  # NOTE:`bash -c`を利用しない配列で書くパターンだと、Secret経由の環境変数を埋め込めなかった
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
        --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
        --region ${_LOCATION} \
        --min-instances=0 \
        --max-instances=1 \
        --allow-unauthenticated \
        --set-env-vars=PROJECT_ID=$PROJECT_ID \
        --set-cloudsql-instances=$$LEGACY_MYSQL_INSTANCE \
        --set-env-vars=LEGACY_MYSQL_PASSWORD=$$LEGACY_MYSQL_PASSWORD \
        --set-env-vars=LEGACY_MYSQL_UNIX_SOCKET=$$LEGACY_MYSQL_UNIX_SOCKET \
        --set-env-vars=LEGACY_MYSQL_USER_NAME=$$LEGACY_MYSQL_USER_NAME \
        --set-env-vars=MULE_API_CLIENT_ID=$$MULE_API_CLIENT_ID \
        --set-env-vars=MULE_API_CLIENT_SECRET=$$MULE_API_CLIENT_SECRET \
        --set-env-vars=CAINZAPP_API_KEY=$$CAINZAPP_API_KEY
    secretEnv:
      [
        'CAINZAPP_API_KEY',
        'LEGACY_MYSQL_PASSWORD',
        'LEGACY_MYSQL_USER_NAME',
        'LEGACY_MYSQL_UNIX_SOCKET',
        'LEGACY_MYSQL_INSTANCE',
        'MULE_API_CLIENT_ID',
        'MULE_API_CLIENT_SECRET',
      ]
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
substitutions:
  _LOCATION: 'asia-northeast1'
  _SERVICE_NAME: 'floormap'
  _DOCKER_FILE: 'apps/api/floormap/Dockerfile'
  _ENV_CONFIG_FILE_NAME: '.env.backend.dev'
  _CLOUD_BUILD_REPOSITORY: 'backend'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/cainzapp_api_key/versions/latest
      env: 'CAINZAPP_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_password/versions/latest
      env: 'LEGACY_MYSQL_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_unix_socket/versions/latest
      env: 'LEGACY_MYSQL_UNIX_SOCKET'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_user_name/versions/latest
      env: 'LEGACY_MYSQL_USER_NAME'
    - versionName: projects/$PROJECT_ID/secrets/legacy_mysql_instance/versions/latest
      env: 'LEGACY_MYSQL_INSTANCE'
    - versionName: projects/$PROJECT_ID/secrets/mule_api_client_id/versions/latest
      env: 'MULE_API_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/mule_api_client_secret/versions/latest
      env: 'MULE_API_CLIENT_SECRET'
