steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-f',
        '$_DOCKER_FILE',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
        '--build-arg',
        'SERVICE_NAME=${_SERVICE_NAME}',
        '--build-arg',
        'ENV_CONFIG_FILE_NAME=${_ENV_CONFIG_FILE_NAME}',
        '.',
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
      ]
  # NOTE:`bash -c`を利用しない配列で書くパターンだと、Secret経由の環境変数を埋め込めなかった
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
        --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
        --region ${_LOCATION} \
        --min-instances=0 \
        --max-instances=1 \
        --allow-unauthenticated \
        --set-env-vars=GEO_ACC_NUMBER=$$GEO_ACC_NUMBER \
        --set-env-vars=GEO_ADMIN_USER_NAME=$$GEO_ADMIN_USER_NAME \
        --set-env-vars=GEO_ADMIN_PSWD=$$GEO_ADMIN_PSWD \
        --set-env-vars=GEO_ACC_ID=$$GEO_ACC_ID \
        --set-env-vars=GEO_GRP_ID=$$GEO_GRP_ID \
        --set-env-vars=GEO_X_API_KEY=$$GEO_X_API_KEY \
        --set-env-vars=GEO_HMAC_SECRET_KEY=$$GEO_HMAC_SECRET_KEY
    secretEnv:
      [
        'GEO_ACC_NUMBER',
        'GEO_ADMIN_USER_NAME',
        'GEO_ADMIN_PSWD',
        'GEO_ACC_ID',
        'GEO_GRP_ID',
        'GEO_X_API_KEY',
        'GEO_HMAC_SECRET_KEY',
      ]
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
substitutions:
  _LOCATION: 'asia-northeast1'
  _SERVICE_NAME: 'geomagnetism'
  _DOCKER_FILE: 'apps/api/geomagnetism/Dockerfile'
  _ENV_CONFIG_FILE_NAME: '.env.backend.dev'
  _CLOUD_BUILD_REPOSITORY: 'backend'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/geo_acc_number/versions/latest
      env: 'GEO_ACC_NUMBER'
    - versionName: projects/$PROJECT_ID/secrets/geo_admin_user_name/versions/latest
      env: 'GEO_ADMIN_USER_NAME'
    - versionName: projects/$PROJECT_ID/secrets/geo_admin_pswd/versions/latest
      env: 'GEO_ADMIN_PSWD'
    - versionName: projects/$PROJECT_ID/secrets/geo_acc_id/versions/latest
      env: 'GEO_ACC_ID'
    - versionName: projects/$PROJECT_ID/secrets/geo_grp_id/versions/latest
      env: 'GEO_GRP_ID'
    - versionName: projects/$PROJECT_ID/secrets/geo_x_api_key/versions/latest
      env: 'GEO_X_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/geo_hmac_secret_key/versions/latest
      env: 'GEO_HMAC_SECRET_KEY'
