import { ProductItem } from '@cainz-next-gen/order';

const getCartData = {
  productItems: [
    {
      itemId: '48677635-ac6a-4412-8f68-5a933a166a29',
      receivingMethod: '1',
      productId: '4549509524318',
      quantity: 20,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4549509524318',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 10,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: true,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: false,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '0',
        largeSizedProductCategoryEc: '1',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.1,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4549509524318',
            storeCode: '859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4549509524318',
            storeCode: '123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4549509524318',
            storeCode: '859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4549509524317',
            storeCode: '123',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
        createdBy: '',
        createdAt: '',
        updatedBy: '',
        updatedAt: '',
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:07',
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: true,
      checkoutId: '123456',
      checkoutStatus: 'Completed',
      errors: null,
      notifications: null,
      createdAt: '2023-11-14T13:40:20+07:21',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
    {
      itemId: '87092821394372',
      receivingMethod: '1',
      productId: '4549509524317',
      quantity: 20,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4549509524317',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 10,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: true,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: false,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '0',
        largeSizedProductCategoryEc: '1',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.1,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4549509524317',
            storeCode: '859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4549509524317',
            storeCode: '123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4549509524318',
            storeCode: '859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4549509524317',
            storeCode: '123',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
        createdBy: '',
        createdAt: '',
        updatedBy: '',
        updatedAt: '',
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4549509524317',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:08',
          items: [
            {
              productCode: '4549509524317',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: true,
      checkoutId: '123456',
      checkoutStatus: 'In-progress',
      errors: null,
      notifications: null,
      createdAt: '2023-11-14T13:40:21+09:00',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
    {
      itemId: '48677635-ac6a-4412-8f68-5a933a166a27',
      receivingMethod: '1',
      productId: '4550414010783',
      quantity: 20,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4550414010783',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 10,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: true,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: false,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '0',
        largeSizedProductCategoryEc: '1',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.1,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4550414010783',
            storeCode: '859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4550414010783',
            storeCode: '123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4550414010783',
            storeCode: '859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4550414010783',
            storeCode: '123',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
        createdBy: '',
        createdAt: '',
        updatedBy: '',
        updatedAt: '',
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4550414010783',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:08',
          items: [
            {
              productCode: '4550414010783',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: true,
      checkoutId: '123456',
      checkoutStatus: 'In-progress',
      errors: null,
      notifications: null,
      createdAt: '2023-11-14T13:40:21+09:00',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
  ],
  storeInfo: {
    code: '859',
    name: 'カインズ本庄早稲田店',
    webUrl: 'https://map.cainz.com/detail/859/',
    address: '〒351-0005 埼玉県朝霞市根岸台3丁目20番1号',
    postCode: '351-0005',
    telNumberList: [
      {
        contactName: '本館',
        telNumber: '048-468-0111',
      },
    ],
    businessTime: '9:00〜20:00',
    businessTimeNote: '本館以外は19:00閉店',
    regularHoliday: '1月1日',
    regularHolidayNote: 'その他不定休あり',
    webOpenStoreFlag: true,
    detail: {
      code: '813',
      landscape: {
        latitude: 35.808684,
        longitude: 139.610384,
      },
      floorGuideList: [
        {
          floorGuideOrder: 1,
          floorGuideName: '本館',
          floorGuidePdfUrl:
            'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FPDF%2F859_1_%E6%9C%AC%E9%A4%A8.pdf?alt=media',
          floorGuideUrl:
            'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FJPG%2F859_1_%E6%9C%AC%E9%A4%A8.jpg?alt=media',
        },
      ],
      prefectureName: '埼玉県',
      prefectureCode: '11',
      regionCode: '03',
      regionName: '関東地方',
      openingDate: '2020-09-23T00:00:00Z',
      closingDate: '9999-12-31T00:00:00Z',
      closedMessage: '閉店',
      supportPickup: true,
      supportCredit: true,
      supportPickupInnerLocker: true,
      supportPickupPlace: true,
      supportPickupPlaceParking: true,
      supportBackOrder: true,
      supportGeomagnetism: true,
      geomagnetismMapId: 'b8e3ef31b120404b848aa9fe1f66fc5a',
      supportPocketRegi: true,
      supportCuttingService: false,
      webCuttingServiceUrl: 'https://www.cainz.co.jp/store_cutting/813',
      supportDIYReserve: true,
      webDIYReserveUrl: 'https://reserve.cainz.com/store/813',
      supportDogRun: true,
      webDogRunUrl: 'https://dogrun.cainz.com/',
      supportToolRental: true,
      webToolRentalUrl: 'https://reserve.cainz.com/store/813/',
      showVisitingNumber: 0,
      toCloseSettings: [
        {
          toCloseType: 'message',
          toCloseFrom: '2021-12-29T20:00:00Z',
          toCloseUntil: '2022-01-03T20:00:00Z',
          toCloseMessage:
            '年末年始の営業時間は下記の店舗詳細WEBページからご確認ください。',
        },
      ],
      storeAreaCode: '09',
      storeAreaName: '埼玉第1エリア',
      searchWords: 'あさかｱｻｶアサカ',
      digitalFlyerURL: 'https://www.shufoo.net/pntweb/shopDetail/235839/',
      materialHallExistence: true,
      cultureClassExistence: false,
      cycleParkExistence: true,
      DIYSTYLEFloorExistence: true,
      dogParkExistence: true,
      exteriorPlazaExistence: true,
      foodAreaExistence: false,
      gardeningHallExistence: false,
      greenAdvisorExistence: false,
      petsOneExistence: true,
      reformCenterExistence: true,
      workshopExistence: false,
      storePickupExistence: true,
      supermarketExistence: true,
    },
    announcements: [
      {
        code: '813',
        title: '写真プリントキャンペーン',
        body: "開催日：2023年5月15日～2023年6月19日\rイベント内容：\r昔撮った思い出のビデオテープ …時が経つにつれテープの劣化やハード機器の故障等で観たいときに観れなくなるかもしれません。この機会に大切な動画をDVDに、音楽等をCDにダビングしてみませんか？\r2023年5月15日より2023年6月19日までの期間中、テープ5本以上のご注文で1本980円（税込）でお受け致します。（通常：10本以上のご注文で1本980円）各店サービスカウンターにて承りますので是非ご利用願います。\r問い合わせ先：サービスカウンター受付\r\r<b>くみまちモールあさか</b>\rカインズとイトーヨーカドーと30の専門店がスマートなくらしを応援します。\r<a href='https://cainz-kumimachi-asaka.com/' target='_blank'>詳細はこちら</a>",
      },
    ],
  },
  estimatedPickupableDateTime: '2023-11-01 09:00',
  shippingAddress: {
    postalCode: '3670012',
    prefecture: '埼玉県',
    city: '本庄市',
  },
  amountInfo: {
    totalProductAmount: 12345,
    basicShippingCost: 9000,
    regionalShippingCost: 7000,
    totalIndividualShippingCost: 1200,
    totalGrossAmount: 20000,
    priceToFreeBasicShipping: 32000,
  },
  storeItemCount: 2,
  shippingItemCount: 2,
  amazonPayButtonConfig: {
    sandbox: false,
    merchantId: '1234',
    ledgerCurrency: '円',
    checkoutLanguage: '日本語',
    productType: '1',
    placement: '1',
    buttonColor: 'ライトグレー',
    estimatedOrderAmount: {
      amount: 1000,
      currency_code: 'JPY',
    },
    createCheckoutSessionConfig: {
      payloadJSON: 'a@er4578',
      signature: '0qwe0987fty6523',
      publicKeyId: 'a1234@#890',
      algorithm: 'SHA-224',
    },
  },
};

const updateCartChangeData = {
  productItems: [
    {
      itemId: '17392851394179',
      receivingMethod: '1',
      productId: '4549509524318',
      quantity: 20,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4549509524318',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 10,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: true,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: false,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '0',
        largeSizedProductCategoryEc: '1',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.1,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4549509524318',
            storeCode: '859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4549509524318',
            storeCode: '123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4549509524318',
            storeCode: '859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4549509524318',
            storeCode: '123',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:07',
          items: [
            {
              productCode: '4549509524318',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: false,
      checkoutId: '123456',
      checkoutStatus: 'Completed',
      createdAt: '2023-11-14T13:40:20+07:21',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
    {
      itemId: '87092821394372',
      receivingMethod: '1',
      productId: '4549509524317',
      quantity: 20,
      orderSpecification: {
        simulationNumber: '980089',
        height: 90,
        width: 200,
        hook: 'A',
      },
      product: {
        productId: '4549509524317',
        name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
        categoryId: 'c2320',
        imageUrls: [
          'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
          'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
        ],
        departmentCode: '014',
        lineCode: '221',
        classCode: '1400',
        description: '',
        applicableStartDate: '2023-05-24T02:00:10.000Z',
        salesStartDate: '2023-05-24T02:00:10.000Z',
        consumptionTaxRate: 10,
        consumptionTaxCategory: '',
        salesEndDate: '2023-05-24T02:00:10.000Z',
        salesEndFlag: false,
        designatedPharmaceuticalCategory: '0',
        liquorCategory: '0',
        tobaccoCategory: '0',
        hazardousMaterialFlag: false,
        medicalEquipmentClass: '',
        poisonousDeleteriousSubstanceCategory: '0',
        poisonousDrugCategory: '0',
        agriculturalChemicalCategory: '0',
        animalDrugCategory: '0',
        warrantyIssuanceCategory: '0',
        pharmaceuticalFlag: false,
        salesTypeCategory: '0',
        warrantyCategory: '0',
        warrantyPeriod: '1年間',
        deliveryChargeCategoryEc: '0',
        onlineFlagEc: true,
        onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
        onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
        consumptionTaxCategoryEc: '0',
        onlineSalesCategoryEc: '0',
        individualDeliveryChargeEc: 600,
        setProductFlag: false,
        configurationFlag: false,
        customizedProductCategory: '0',
        minOrderQuantity: 1,
        maxOrderQuantity: 100,
        stepQuantity: 1,
        storeMinOrderQuantity: 1,
        storeMaxOrderQuantity: 100,
        storeStepOrderQuantity: 1,
        newPeriodFrom: '2023-05-24T02:00:10.000Z',
        reserveFromStoreDisabled: false,
        sendToStoreDisabled: false,
        personalDeliveryDisabled: false,
        estimatedArrivalDays: 3,
        productWithServiceFlag: false,
        dropShippingCategory: '0',
        largeSizedProductCategoryEc: '1',
        originCountryCode: 'JP',
        flavorExpirationCategory: '0',
        flavorExpiration: 3,
        productCharacteristics:
          'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
        colorPattern: '黒',
        size: '',
        brandName: '',
        singleItemSizeWidth: 19.1,
        singleItemSizeHeight: 5.1,
        singleItemSizeDepth: 7.7,
        contentAmount: 10,
        contentAmountUnit: 'L',
        modelNo: '',
        lawsStandards: 'JIS',
        singleItemSize2Width: 19.1,
        singleItemSize2Height: 5.1,
        singleItemSize2Depth: 7.7,
        specCategory: [
          {
            name: 'カラー',
            value: '',
          },
          {
            name: '本体サイズ-幅(cm)',
            value: '19',
          },
          {
            name: '本体サイズ-奥行(cm)',
            value: '14.5',
          },
        ],
        characterCopyrightNameEc: '',
        longDescription:
          "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます",
        cautions:
          '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
        productSpecGroupId: '',
        similarProduct: '',
        recommendedProduct: '',
        comparativeProduct: '',
        kukuru: '00000152',
        variation: [
          {
            name: '01-001',
            value: '4',
          },
          {
            name: '01-001',
            value: '4',
          },
        ],
        faceProductId: '00000152',
        serviceContents: '',
        prices: [
          {
            productId: '4549509524317',
            storeCode: '859',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
          {
            productId: '4549509524317',
            storeCode: '123',
            membershipRank: '4',
            priceIncludingTax: 8980,
            salePriceIncludingTax: 7980,
          },
        ],
        inventories: [
          {
            productId: '4549509524317',
            storeCode: '859',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
            expectedArrivalDate: '2023-03-03T00:00:00.000Z',
          },
          {
            productId: '4549509524317',
            storeCode: '123',
            quantityOpening: 10,
            quantitySold: 3,
            quantityAvailable: 6,
            quantityAllocated: 1,
            quantityExpected: 3,
          },
        ],
      },
      delivery: {
        shipping: {
          estimatedDate: '2023-06-23',
          canSelectDate: false,
          items: [
            {
              productCode: '4549509524317',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
        pickup: {
          dateTime: '2023-06-23 09:08',
          items: [
            {
              productCode: '4549509524317',
              estimatedDate: '2023-06-23',
              isSeparate: false,
            },
          ],
        },
      },
      setProductType: '0',
      isReserveFromStoreAvailable: true,
      isPersonalDeliveryAvailable: true,
      invalidWebBackOrderFlagForStorePickup: false,
      invalidWebBackOrderFlagForDesignatedDelivery: true,
      isWebBackOrder: false,
      unitPrice: 2000,
      subtotalProductAmount: 10000,
      individualShippingCost: 4000,
      subtotalIndividualShippingCost: 3200,
      campaignPoints: 1800,
      subtotalCampaignPoints: 3600,
      isCheckoutTarget: false,
      checkoutId: '123456',
      checkoutStatus: 'In-progress',
      createdAt: '2023-11-14T13:40:21+09:00',
      updatedAt: '2023-11-15T13:40:21+09:00',
    },
  ],
  storeInfo: {
    code: '859',
    name: 'カインズ本庄早稲田店',
    webUrl: 'https://map.cainz.com/detail/859/',
    address: '〒351-0005 埼玉県朝霞市根岸台3丁目20番1号',
    postCode: '351-0005',
    telNumberList: [
      {
        contactName: '本館',
        telNumber: '048-468-0111',
      },
    ],
    businessTime: '9:00〜20:00',
    businessTimeNote: '本館以外は19:00閉店',
    regularHoliday: '1月1日',
    regularHolidayNote: 'その他不定休あり',
    webOpenStoreFlag: true,
    detail: {
      code: '813',
      landscape: {
        latitude: 35.808684,
        longitude: 139.610384,
      },
      floorGuideList: [
        {
          floorGuideOrder: 1,
          floorGuideName: '本館',
          floorGuidePdfUrl:
            'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FPDF%2F859_1_%E6%9C%AC%E9%A4%A8.pdf?alt=media',
          floorGuideUrl:
            'https://firebasestorage.googleapis.com/v0/b/prd-cainz-app-cust1/o/cainz%2FfloorGuide%2FJPG%2F859_1_%E6%9C%AC%E9%A4%A8.jpg?alt=media',
        },
      ],
      prefectureName: '埼玉県',
      prefectureCode: '11',
      regionCode: '03',
      regionName: '関東地方',
      openingDate: '2020-09-23T00:00:00Z',
      closingDate: '9999-12-31T00:00:00Z',
      closedMessage: '閉店',
      supportPickup: true,
      supportCredit: true,
      supportPickupInnerLocker: true,
      supportPickupPlace: true,
      supportPickupPlaceParking: true,
      supportBackOrder: true,
      supportGeomagnetism: true,
      geomagnetismMapId: 'b8e3ef31b120404b848aa9fe1f66fc5a',
      supportPocketRegi: true,
      supportCuttingService: false,
      webCuttingServiceUrl: 'https://www.cainz.co.jp/store_cutting/813',
      supportDIYReserve: true,
      webDIYReserveUrl: 'https://reserve.cainz.com/store/813',
      supportDogRun: true,
      webDogRunUrl: 'https://dogrun.cainz.com/',
      supportToolRental: true,
      webToolRentalUrl: 'https://reserve.cainz.com/store/813/',
      showVisitingNumber: 0,
      toCloseSettings: [
        {
          toCloseType: 'message',
          toCloseFrom: '2021-12-29T20:00:00Z',
          toCloseUntil: '2022-01-03T20:00:00Z',
          toCloseMessage:
            '年末年始の営業時間は下記の店舗詳細WEBページからご確認ください。',
        },
      ],
      storeAreaCode: '09',
      storeAreaName: '埼玉第1エリア',
      searchWords: 'あさかｱｻｶアサカ',
      digitalFlyerURL: 'https://www.shufoo.net/pntweb/shopDetail/235839/',
      materialHallExistence: true,
      cultureClassExistence: false,
      cycleParkExistence: true,
      DIYSTYLEFloorExistence: true,
      dogParkExistence: true,
      exteriorPlazaExistence: true,
      foodAreaExistence: false,
      gardeningHallExistence: false,
      greenAdvisorExistence: false,
      petsOneExistence: true,
      reformCenterExistence: true,
      workshopExistence: false,
      storePickupExistence: true,
      supermarketExistence: true,
    },
    announcements: [
      {
        code: '813',
        title: '写真プリントキャンペーン',
        body: "開催日：2023年5月15日～2023年6月19日\rイベント内容：\r昔撮った思い出のビデオテープ …時が経つにつれテープの劣化やハード機器の故障等で観たいときに観れなくなるかもしれません。この機会に大切な動画をDVDに、音楽等をCDにダビングしてみませんか？\r2023年5月15日より2023年6月19日までの期間中、テープ5本以上のご注文で1本980円（税込）でお受け致します。（通常：10本以上のご注文で1本980円）各店サービスカウンターにて承りますので是非ご利用願います。\r問い合わせ先：サービスカウンター受付\r\r<b>くみまちモールあさか</b>\rカインズとイトーヨーカドーと30の専門店がスマートなくらしを応援します。\r<a href='https://cainz-kumimachi-asaka.com/' target='_blank'>詳細はこちら</a>",
      },
    ],
  },
  estimatedPickupableDateTime: '2023-11-01 09:00',
  shippingAddress: {
    addressBookId: '1',
    zipCode: '3670012',
    prefecture: '埼玉県',
    city: '本庄市',
  },
  amountInfo: {
    totalProductAmountStore: 4600,
    totalProductAmountEc: 12345,
    basicShippingCost: 9000,
    regionalShippingCost: 7000,
    totalIndividualShippingCost: 1200,
    totalGrossAmount: 20000,
    priceToFreeBasicShipping: 32000,
  },
  storeItemCount: 2,
  shippingItemCount: 2,
  amazonPayButtonConfig: {
    sandbox: false,
    merchantId: '1234',
    ledgerCurrency: '円',
    checkoutLanguage: '日本語',
    productType: '1',
    placement: '1',
    buttonColor: 'ライトグレー',
    estimatedOrderAmount: {
      amount: 1000,
      currency_code: 'JPY',
    },
    createCheckoutSessionConfig: {
      payloadJSON: 'a@er4578',
      signature: '0qwe0987fty6523',
      publicKeyId: 'a1234@#890',
      algorithm: 'SHA-224',
    },
  },
};

const anonymousUserdata = [
  {
    userId: '07P1He8a0Ze4OlTCpWf3D3M469P2',
    productItems: [
      {
        itemId: '4549509524318',
        receivingMethod: '1',
        productId: '4549509524318',
        quantity: 20,
        orderSpecification: {
          simulationNumber: '980089',
          height: 90,
          width: 200,
          hook: 'A',
        },
        product: {
          productId: '4549509524318',
          imageUrls: [
            'https://imgix.cainz.com/4906128451037/product/4906128451037_01.jpg?auto=format,compress&w=691&h=691&fit=fill&fill=solid&fill-color=white',
          ],
          liquorCategory: '1',
          deliveryChargeCategoryEc: '1',
          onlineFlagEc: false,
          onlineStartTimeEc: '23/12/23',
          onlineEndTimeEc: '24/12/23',
          onlineSalesCategoryEc: '1',
          individualDeliveryChargeEc: '1',
          minOrderQuantity: '5',
          maxOrderQuantity: '10',
          stepQuantity: '5',
          storeMyOrderQuantity: '5',
          storeMaxOrderQuantity: '10',
          storeStepOrderQuantity: '10',
          reserveFromStoreDisabled: false,
          sendToStoreDisabled: false,
          personalDeliveryDisabled: false,
          dropShippingCategory: '1',
        },
        delivery: {
          deliveryChargeCategoryEc: '2',
          individualDeliveryChargeEc: null,
          pickupDate: {
            _seconds: 1697518636,
            _nanoseconds: 223000000,
          },
          deliveryTypeCategory: '1',
          deliveryDate: {
            _seconds: 1697518636,
            _nanoseconds: 223000000,
          },
          personalDeliveryDisabled: '0',
        },
        setProductType: '0',
        invalidWebBackOrderFlagForStorePickup: false,
        invalidWebBackOrderFlagForDesignatedDelivery: true,
        isWebBackOrder: false,
        unitPrice: 2000,
        subtotalProductAmount: 10000,
        individualShippingCost: 4000,
        subtotalIndividualShippingCost: 3200,
        isCheckoutTarget: false,
        checkoutId: '123456',
        checkoutStatus: 'Completed',
        errors: null,
        notifications: [
          {
            messageCode: 100,
            description:
              '【期間限定 個別送料無料】コロナ 石油ファンヒーター 鉄筋12畳木造9畳程度 シェルホワイト FHG3223YW【別送品】',
          },
        ],
        createdAt: '05/02/2022',
        updatedAt: '09/12/2022',
      },
      {
        itemId: '4549509524319',
        receivingMethod: '1',
        productId: '4549509524318',
        quantity: 2000,
        orderSpecification: {
          simulationNumber: '980089',
          height: 90,
          width: 200,
          hook: 'A',
        },
        product: {
          productId: '4549509524318',
          imageUrls: [
            'https://imgix.cainz.com/4906128451037/product/4906128451037_01.jpg?auto=format,compress&w=691&h=691&fit=fill&fill=solid&fill-color=white',
          ],
          liquorCategory: '1',
          deliveryChargeCategoryEc: '1',
          onlineFlagEc: false,
          onlineStartTimeEc: '23/12/23',
          onlineEndTimeEc: '24/12/23',
          onlineSalesCategoryEc: '1',
          individualDeliveryChargeEc: '1',
          minOrderQuantity: '5',
          maxOrderQuantity: '10',
          stepQuantity: '5',
          storeMyOrderQuantity: '5',
          storeMaxOrderQuantity: '10',
          storeStepOrderQuantity: '10',
          reserveFromStoreDisabled: false,
          sendToStoreDisabled: false,
          personalDeliveryDisabled: false,
          dropShippingCategory: '1',
        },
        delivery: {
          deliveryChargeCategoryEc: '2',
          individualDeliveryChargeEc: null,
          pickupDate: {
            _seconds: 1697518636,
            _nanoseconds: 223000000,
          },
          deliveryTypeCategory: '1',
          deliveryDate: {
            _seconds: 1697518636,
            _nanoseconds: 223000000,
          },
          personalDeliveryDisabled: '0',
        },
        setProductType: '0',
        invalidWebBackOrderFlagForStorePickup: false,
        invalidWebBackOrderFlagForDesignatedDelivery: true,
        isWebBackOrder: false,
        unitPrice: 2000,
        subtotalProductAmount: 10000,
        individualShippingCost: 4000,
        subtotalIndividualShippingCost: 3200,
        isCheckoutTarget: false,
        checkoutId: '123456',
        checkoutStatus: 'Completed',
        errors: null,
        notifications: [
          {
            messageCode: 100,
            description:
              '【期間限定 個別送料無料】コロナ 石油ファンヒーター 鉄筋12畳木造9畳程度 シェルホワイト FHG3223YW【別送品】',
          },
        ],
        createdAt: '05/02/2022',
        updatedAt: '09/12/2022',
      },
    ],
    storeInfo: {
      store_code: '0760',
      branchNumber: '1234',
      storeName: 'カインズ伊勢崎',
      storeNameKatakana: 'カインズ伊勢崎',
      postalCode: '3670012',
      address: ' 愛知県小牧市大字二重堀字芒原８１',
      addressKatakana: '愛知県小牧市大字二重堀字芒原８１',
      phone: '0568-42-6000',
      storeClass: 'A',
    },
    estimatedPickupableDateTime: '翌日 11/10(金) 最短10:00以降受取可',
    shippingAddress: {
      postalCode: '3670012',
      prefecture: '愛知',
      city: '小牧',
      addressBookId: '123',
    },
    amountInfo: {
      totalProductAmount: 12345,
      basicShippingCost: 9000,
      regionalShippingCost: 7000,
      totalIndividualShippingCost: 1200,
      totalGrossAmount: 20000,
      priceToFreeBasicShipping: 32000,
    },
    storeItemCount: 2,
    shippingItemCount: 2,
    notifications: [
      {
        messageCode: 100,
        description:
          '【期間限定 個別送料無料】コロナ 石油ファンヒーター 鉄筋12畳木造9畳程度 シェルホワイト FHG3223YW【別送品】',
      },
    ],
    amazonPayButtonConfig: {
      sandbox: false,
      merchantId: '1234',
      ledgerCurrency: '円',
      checkoutLanguage: '日本語',
      productType: '1',
      placement: '1',
      buttonColor: 'ライトグレー',
      estimatedOrderAmount: {
        amount: 1000,
        currency_code: 'JPY',
      },
      createCheckoutSessionConfig: {
        payloadJSON: 'a@er4578',
        signature: '0qwe0987fty6523',
        publicKeyId: 'a1234@#890',
        algorithm: 'SHA-224',
      },
    },
  },
];

const membersData = [
  {
    userId: '07P1He8a0Ze4OlTCpWf3F3M469H1',
    productItems: [
      {
        itemId: '4549509524318',
        receivingMethod: '1',
        productId: '4549509524318',
        quantity: 20,
        orderSpecification: {
          simulationNumber: '980089',
          height: 90,
          width: 200,
          hook: 'A',
        },
        product: {
          productId: '4549509524318',
          imageUrls: [
            'https://imgix.cainz.com/4906128451037/product/4906128451037_01.jpg?auto=format,compress&w=691&h=691&fit=fill&fill=solid&fill-color=white',
          ],
          liquorCategory: '1',
          deliveryChargeCategoryEc: '1',
          onlineFlagEc: false,
          onlineStartTimeEc: '23/12/23',
          onlineEndTimeEc: '24/12/23',
          onlineSalesCategoryEc: '1',
          individualDeliveryChargeEc: '1',
          minOrderQuantity: '5',
          maxOrderQuantity: '10',
          stepQuantity: '5',
          storeMyOrderQuantity: '5',
          storeMaxOrderQuantity: '10',
          storeStepOrderQuantity: '10',
          reserveFromStoreDisabled: false,
          sendToStoreDisabled: false,
          personalDeliveryDisabled: false,
          dropShippingCategory: '1',
        },
        delivery: {
          deliveryChargeCategoryEc: '2',
          individualDeliveryChargeEc: null,
          pickupDate: {
            _seconds: 1697518636,
            _nanoseconds: 223000000,
          },
          deliveryTypeCategory: '1',
          deliveryDate: {
            _seconds: 1697518636,
            _nanoseconds: 223000000,
          },
          personalDeliveryDisabled: '0',
        },
        setProductType: '0',
        invalidWebBackOrderFlagForStorePickup: false,
        invalidWebBackOrderFlagForDesignatedDelivery: true,
        isWebBackOrder: false,
        unitPrice: 2000,
        subtotalProductAmount: 10000,
        individualShippingCost: 4000,
        subtotalIndividualShippingCost: 3200,
        isCheckoutTarget: false,
        checkoutId: '123456',
        checkoutStatus: 'Completed',
        errors: null,
        notifications: [
          {
            messageCode: 100,
            description:
              '【期間限定 個別送料無料】コロナ 石油ファンヒーター 鉄筋12畳木造9畳程度 シェルホワイト FHG3223YW【別送品】',
          },
        ],
        createdAt: '05/02/2022',
        updatedAt: '09/12/2022',
      },
    ],
    storeInfo: {
      store_code: '0760',
      branchNumber: '1234',
      storeName: 'カインズ伊勢崎',
      storeNameKatakana: 'カインズ伊勢崎',
      postalCode: '3670012',
      address: ' 愛知県小牧市大字二重堀字芒原８１',
      addressKatakana: '愛知県小牧市大字二重堀字芒原８１',
      phone: '0568-42-6000',
      storeClass: 'A',
    },
    estimatedPickupableDateTime: '翌日 11/10(金) 最短10:00以降受取可',
    shippingAddress: {
      postalCode: '3670012',
      prefecture: '愛知',
      city: '小牧',
      addressBookId: '123',
    },
    amountInfo: {
      totalProductAmount: 12345,
      basicShippingCost: 9000,
      regionalShippingCost: 7000,
      totalIndividualShippingCost: 1200,
      totalGrossAmount: 20000,
      priceToFreeBasicShipping: 32000,
    },
    storeItemCount: 2,
    shippingItemCount: 2,
    notifications: [
      {
        messageCode: 100,
        description:
          '【期間限定 個別送料無料】コロナ 石油ファンヒーター 鉄筋12畳木造9畳程度 シェルホワイト FHG3223YW【別送品】',
      },
    ],
    amazonPayButtonConfig: {
      sandbox: false,
      merchantId: '1234',
      ledgerCurrency: '円',
      checkoutLanguage: '日本語',
      productType: '1',
      placement: '1',
      buttonColor: 'ライトグレー',
      estimatedOrderAmount: {
        amount: 1000,
        currency_code: 'JPY',
      },
      createCheckoutSessionConfig: {
        payloadJSON: 'a@er4578',
        signature: '0qwe0987fty6523',
        publicKeyId: 'a1234@#890',
        algorithm: 'SHA-224',
      },
    },
  },
];

const userInfo = {
  isMember: true,
  billPayment: true,
  zipCode: '123456',
  prefecture: '埼玉県',
};

const itemData = {
  receivingMethod: '1',
  productId: '4549509524318',
  quantity: 15,
  orderSpecification: {
    simulationNumber: '',
    height: 10,
    width: 10,
    hook: '',
  },
};

const products = [
  {
    productId: '4549509524318',
    name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
    categoryId: 'c2320',
    imageUrls: [
      'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
    ],
    departmentCode: '014',
    lineCode: '221',
    classCode: '1400',
    description: '',
    applicableStartDate: '2023-05-24T02:00:10.000Z',
    salesStartDate: '2023-05-24T02:00:10.000Z',
    consumptionTaxRate: 10,
    consumptionTaxCategory: '',
    salesEndDate: '2023-05-24T02:00:10.000Z',
    salesEndFlag: false,
    designatedPharmaceuticalCategory: '0',
    liquorCategory: '0',
    tobaccoCategory: '0',
    hazardousMaterialFlag: false,
    medicalEquipmentClass: '',
    poisonousDeleteriousSubstanceCategory: '0',
    poisonousDrugCategory: '0',
    agriculturalChemicalCategory: '0',
    animalDrugCategory: '0',
    warrantyIssuanceCategory: '0',
    pharmaceuticalFlag: false,
    salesTypeCategory: '0',
    warrantyCategory: '0',
    warrantyPeriod: '1年間',
    deliveryChargeCategoryEc: '5',
    onlineFlagEc: true,
    onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
    onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
    consumptionTaxCategoryEc: '0',
    onlineSalesCategoryEc: '1',
    individualDeliveryChargeEc: 600,
    setProductFlag: false,
    configurationFlag: false,
    customizedProductCategory: '1',
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    stepQuantity: 1,
    storeMinOrderQuantity: 1,
    storeMaxOrderQuantity: 100,
    storeStepOrderQuantity: 1,
    newPeriodFrom: '2023-05-24T02:00:10.000Z',
    reserveFromStoreDisabled: false,
    sendToStoreDisabled: false,
    personalDeliveryDisabled: false,
    estimatedArrivalDays: 3,
    productWithServiceFlag: false,
    dropShippingCategory: '1',
    largeSizedProductCategoryEc: '0',
    originCountryCode: 'JP',
    flavorExpirationCategory: '0',
    flavorExpiration: 3,
    productCharacteristics:
      'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
    colorPattern: '黒',
    size: '',
    brandName: '',
    singleItemSizeWidth: 19.1,
    singleItemSizeHeight: 5.1,
    singleItemSizeDepth: 7.7,
    contentAmount: 10,
    contentAmountUnit: 'L',
    modelNo: '',
    lawsStandards: 'JIS',
    singleItemSize2Width: 19.1,
    singleItemSize2Height: 5.1,
    singleItemSize2Depth: 7.7,
    specCategory: [
      {
        name: 'カラー',
        value: '',
      },
      {
        name: '本体サイズ-幅(cm)',
        value: '19',
      },
      {
        name: '本体サイズ-奥行(cm)',
        value: '14.5',
      },
    ],
    characterCopyrightNameEc: '',
    longDescription:
      "<p class='m-bold'>大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ!</p>\\\\r\\\\n\\\\r\\\\n<ul class='m-listDot'>\\\\r\\\\n  <li>固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。</li>\\\\r\\\\n  <li>おからが主原料なので燃やすことができます。</li>\\\\r\\\\n  <li>生ごみとしても処理できます。</li>\\\\r\\\\n  <li>消臭</li>\\\\r\\\\n</ul>\\\\r\\\\n\\\\r\\\\n",
    cautions: '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
    productSpecGroupId: '',
    similarProduct: '',
    recommendedProduct: '',
    comparativeProduct: '',
    kukuru: '00000152',
    variation: [
      {
        name: '01-001',
        value: '4',
      },
      {
        name: '01-001',
        value: '4',
      },
    ],
    faceProductId: '00000152',
    serviceContents: '',
    prices: [
      {
        productId: '4549509646945',
        storeCode: '859',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
      {
        productId: '4549509646945',
        storeCode: '123',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
    ],
    inventories: [
      {
        productId: '4549509646952',
        storeCode: '859',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
        expectedArrivalDate: '2023-03-03T00:00:00.000Z',
      },
      {
        productId: '4549509646952',
        storeCode: '123',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
      },
    ],
    createdBy: '',
    createdAt: '',
    updatedBy: '',
    updatedAt: '',
  },
];

const emptyProductItem: ProductItem = {
  itemId: null,
  receivingMethod: null,
  productId: null,
  quantity: null,
  orderSpecification: undefined,
  product: undefined,
  invalidWebBackOrderFlagForStorePickup: null,
  invalidWebBackOrderFlagForDesignatedDelivery: null,
  unitPriceForStorePickup: 0,
  unitPriceForDelivery: 0,
  selectedUnitPrice: 0,
  subtotalProductAmount: null,
  individualShippingCost: null,
  subtotalIndividualShippingCost: null,
  campaignPoints: null,
  subtotalCampaignPoints: null,
  isCheckoutTarget: true,
  createdAt: null,
  updatedAt: null,
};
const selectedItems = [
  '48677635-ac6a-4412-8f68-5a933a166a29',
  '87092821394372',
  '48677635-ac6a-4412-8f68-5a933a166a27',
];

const cartData = {
  createdAt: {
    _seconds: 1703583249,
    _nanoseconds: 711000000,
  },
  productItems: getCartData.productItems,
  shippingAddress: null,
  userId: 'RzMlOcujJMZS2CmaBZzD',
  storeCode: null,
  updatedAt: {
    _seconds: 1703583249,
    _nanoseconds: 711000000,
  },
};

const overwriteContent = {
  productItems: getCartData.productItems,
  storeCode: '0809',
  shippingAddress: {
    zipCode: '0809',
    prefecture: 'Hokkaido',
    city: 'Tokyo',
    addressBookId: '123566',
  },
};
export {
  anonymousUserdata,
  membersData,
  getCartData,
  updateCartChangeData,
  userInfo,
  itemData,
  products,
  emptyProductItem,
  selectedItems,
  cartData,
  overwriteContent,
};
