import { HttpException, HttpStatus } from '@nestjs/common';
import { GlobalErrorCode } from '@cainz-next-gen/exception';
import {
  CartErrorMessage,
  CheckoutErrorMessage,
  ErrorCode,
} from '../src/types/constants/error-code';

const mockCheckoutBeginResponse = {
  customerInfo: {
    customerLastName: '埼玉',
    customerFirstName: '太郎',
    customerLastNameKana: 'サイタマ',
    customerFirstNameKana: 'タロウ',
    customerZipCode: '3671234',
    customerPrefecture: '埼玉県',
    customerCity: '本庄市',
    customerAddress1: '早稲田の杜一丁目９９番９９９号',
    customerAddress2: 'カインズビル',
    customerCompanyName: '株式会社　ECリプレイス',
    customerDepartmentName: '情報システム部',
    customerPhone: '0120999999',
    customerEmail: 'Taro@test.co.jp',
  },
  storeInfo: {
    storeCode: '0760',
    storeName: 'カインズ伊勢崎',
    storeHours: '09:00 ～ 20:00',
    zipCode: '3720999',
    address: '群馬県伊勢崎市宮子町９９９９',
    supportPickupInnerLocker: true,
    supportPickupPlace: true,
    supportPickupPlaceParking: true,
    selectedReceiptLocation: '3',
    supportCredit: true,
    mapUrl: 'https://map.test.com/map/999',
    estimatedPickupableDateTime: '本日 11/16(木) 最短13:00以降受取可',
  },
  addressBookList: [
    {
      addressBookId: '1',
      lastName: '配送先',
      firstName: '太郎',
      lastNameKana: 'ハイソウサキ',
      firstNameKana: 'タロウ',
      zipCode: '5300000',
      prefecture: '大阪府',
      city: '大阪市北区',
      address1: '梅田一丁目',
      address2: '梅田ビル９９階',
      companyName: 'テスト株式会社',
      departmentName: 'テスト部',
      phone: '069999999',
      isPreferredAddress: true,
      isSelected: true,
    },
  ],
  shippingInfo: {
    shippingLastName: 'お届け先',
    shippingFirstName: '太郎',
    shippingLastNameKana: 'オトドケサキ',
    shippingFirstNameKana: 'タロウ',
    shippingZipCode: '0790000',
    shippingPrefecture: '北海道',
    shippingCity: '赤平市',
    shippingAddress1: '赤平１１１丁目',
    shippingAddress2: '赤平マンション１号室',
    shippingCompanyName: '株式会社　北海道',
    shippingDepartmentName: '情報システム部',
    shippingPhone: '12599999999',
    selectedAddressBookId: '2',
    desiredDeliveryDateList: [
      {
        availableDeliveryDate: '2023-11-17T18:00:00.000Z',
        isSelected: false,
      },
      {
        availableDeliveryDate: '2023-11-18T18:00:00.000Z',
        isSelected: true,
      },
    ],
    desiredDeliveryTimeZoneList: [
      {
        availableDeliveryTimeZoneId: '0',
        availableDeliveryTimeZoneName: '14~16時',
        isSelected: true,
      },
    ],
    isDeliveryBox: false,
    isGift: false,
  },
  paymentMethodInfoList: [
    {
      paymentMethodId: '1',
      paymentMethodName: 'クレジットカード',
      paymentMethodDetail: 'ギフトカード',
      registeredCreditCardList: [
        {
          cardSequentialNumber: 0,
          cardNumber: '999999****9999',
          expirationDate: '12/24',
          isDeleted: false,
          isSelected: false,
        },
        {
          cardSequentialNumber: 1,
          cardNumber: '999999****8888',
          expirationDate: '01/26',
          isDeleted: false,
          isSelected: true,
        },
      ],
      convenienceCodeList: [
        {
          convenienceCode: '00007',
          convenienceName: 'セブンイレブン',
          isSelected: false,
        },
      ],
      paymentCharge: 330,
      maxPurchaseAmount: 55000,
      isStorePaymentSelected: false,
      isSaveCard: true,
      numberOfTokensRequired: 2,
      isSelected: true,
    },
  ],
  pointInfo: {
    availablePoints: 1000,
    redeemedPoints: 123,
  },
  storeReceiveProducts: [
    {
      productItems: [
        {
          itemId: '17392851394179',
          receivingMethod: '1',
          productId: '4549509524322',
          quantity: 20,
          orderSpecification: {
            simulationNumber: '980089',
            height: 90,
            width: 200,
            hook: 'A',
          },
          product: {
            productId: '4549509646952',
            name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
            categoryId: 'c2320',
            imageUrls: [
              'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
              'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
              'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
            ],
            departmentCode: '014',
            lineCode: '221',
            classCode: '1400',
            description: '',
            applicableStartDate: '2023-05-24T02:00:10.000Z',
            salesStartDate: '2023-05-24T02:00:10.000Z',
            consumptionTaxRate: 10,
            consumptionTaxCategory: '',
            salesEndDate: '2023-05-24T02:00:10.000Z',
            salesEndFlag: false,
            designatedPharmaceuticalCategory: '0',
            liquorCategory: '0',
            tobaccoCategory: '0',
            hazardousMaterialFlag: false,
            medicalEquipmentClass: '',
            poisonousDeleteriousSubstanceCategory: '0',
            poisonousDrugCategory: '0',
            agriculturalChemicalCategory: '0',
            animalDrugCategory: '0',
            warrantyIssuanceCategory: '0',
            pharmaceuticalFlag: false,
            salesTypeCategory: '0',
            warrantyCategory: '0',
            warrantyPeriod: '1年間',
            deliveryChargeCategoryEc: '0',
            onlineFlagEc: true,
            onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
            onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
            consumptionTaxCategoryEc: '0',
            onlineSalesCategoryEc: '0',
            individualDeliveryChargeEc: 600,
            setProductFlag: false,
            configurationFlag: false,
            customizedProductCategory: '0',
            minOrderQuantity: 1,
            maxOrderQuantity: 100,
            stepQuantity: 1,
            storeMinOrderQuantity: 1,
            storeMaxOrderQuantity: 100,
            storeStepOrderQuantity: 1,
            newPeriodFrom: '2023-05-24T02:00:10.000Z',
            reserveFromStoreDisabled: false,
            sendToStoreDisabled: false,
            personalDeliveryDisabled: false,
            estimatedArrivalDays: 3,
            productWithServiceFlag: false,
            dropShippingCategory: '0',
            originCountryCode: 'JP',
            flavorExpirationCategory: '0',
            flavorExpiration: 3,
            productCharacteristics:
              'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
            colorPattern: '黒',
            size: '',
            brandName: '',
            singleItemSizeWidth: 19.1,
            singleItemSizeHeight: 5.1,
            singleItemSizeDepth: 7.7,
            contentAmount: 10,
            contentAmountUnit: 'L',
            modelNo: '',
            lawsStandards: 'JIS',
            singleItemSize2Width: 19.1,
            singleItemSize2Height: 5.1,
            singleItemSize2Depth: 7.7,
            specCategory: [
              {
                name: 'カラー',
                value: '',
              },
              {
                name: '本体サイズ-幅(cm)',
                value: '19',
              },
              {
                name: '本体サイズ-奥行(cm)',
                value: '14.5',
              },
            ],
            characterCopyrightNameEc: '',
            longDescription:
              "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
            cautions:
              '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
            productSpecGroupId: '',
            similarProduct: '',
            recommendedProduct: '',
            comparativeProduct: '',
            kukuru: '00000152',
            variation: [
              {
                name: '01-001',
                value: '4',
              },
              {
                name: '01-001',
                value: '4',
              },
            ],
            faceProductId: '00000152',
            serviceContents: '',
            prices: [
              {
                productId: '4549509646945',
                storeCodes: '859',
                membershipRank: '4',
                priceIncludingTax: 8980,
                salePriceIncludingTax: 7980,
              },
              {
                productId: '4549509646945',
                storeCodes: '123',
                membershipRank: '4',
                priceIncludingTax: 8980,
                salePriceIncludingTax: 7980,
              },
            ],
            inventories: [
              {
                productId: '4549509646952',
                storeCode: '859',
                quantityOpening: 10,
                quantitySold: 3,
                quantityAvailable: 6,
                quantityAllocated: 1,
                quantityExpected: 3,
                expectedArrivalDate: '2023-03-03T00:00:00.000Z',
              },
              {
                productId: '4549509646952',
                storeCode: '123',
                quantityOpening: 10,
                quantitySold: 3,
                quantityAvailable: 6,
                quantityAllocated: 1,
                quantityExpected: 3,
              },
            ],
          },
          delivery: {
            shipping: {
              estimatedDate: '2023-06-23',
              canSelectDate: false,
              items: [
                {
                  productCode: '4549509524317',
                  estimatedDate: '2023-06-23',
                  isSeparate: false,
                },
              ],
            },
            pickup: {
              dateTime: '2023-06-23 09:07',
              items: [
                {
                  productCode: '4549509524317',
                  estimatedDate: '2023-06-23',
                  isSeparate: false,
                },
              ],
            },
          },
          setProductType: '0',
          isReserveFromStoreAvailable: true,
          isPersonalDeliveryAvailable: true,
          invalidWebBackOrderFlagForStorePickup: false,
          invalidWebBackOrderFlagForDesignatedDelivery: true,
          isWebBackOrder: false,
          unitPrice: 2000,
          subtotalProductAmount: 10000,
          individualShippingCost: 4000,
          subtotalIndividualShippingCost: 3200,
          campaignPoints: 1800,
          subtotalCampaignPoints: 3600,
          isCheckoutTarget: false,
          checkoutId: '123456',
          checkoutStatus: 'Completed',
          createdAt: '2023-11-14T13:40:20+07:21',
          updatedAt: '2023-11-15T13:40:21+09:00',
        },
        {
          itemId: '87092821394372',
          receivingMethod: '1',
          productId: '4549509524323',
          quantity: 20,
          orderSpecification: {
            simulationNumber: '980089',
            height: 90,
            width: 200,
            hook: 'A',
          },
          product: {
            productId: '4549509646952',
            name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
            categoryId: 'c2320',
            imageUrls: [
              'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
              'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
              'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
            ],
            departmentCode: '014',
            lineCode: '221',
            classCode: '1400',
            description: '',
            applicableStartDate: '2023-05-24T02:00:10.000Z',
            salesStartDate: '2023-05-24T02:00:10.000Z',
            consumptionTaxRate: 10,
            consumptionTaxCategory: '',
            salesEndDate: '2023-05-24T02:00:10.000Z',
            salesEndFlag: false,
            designatedPharmaceuticalCategory: '0',
            liquorCategory: '0',
            tobaccoCategory: '0',
            hazardousMaterialFlag: false,
            medicalEquipmentClass: '',
            poisonousDeleteriousSubstanceCategory: '0',
            poisonousDrugCategory: '0',
            agriculturalChemicalCategory: '0',
            animalDrugCategory: '0',
            warrantyIssuanceCategory: '0',
            pharmaceuticalFlag: false,
            salesTypeCategory: '0',
            warrantyCategory: '0',
            warrantyPeriod: '1年間',
            deliveryChargeCategoryEc: '0',
            onlineFlagEc: true,
            onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
            onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
            consumptionTaxCategoryEc: '0',
            onlineSalesCategoryEc: '0',
            individualDeliveryChargeEc: 600,
            setProductFlag: false,
            configurationFlag: false,
            customizedProductCategory: '0',
            minOrderQuantity: 1,
            maxOrderQuantity: 100,
            stepQuantity: 1,
            storeMinOrderQuantity: 1,
            storeMaxOrderQuantity: 100,
            storeStepOrderQuantity: 1,
            newPeriodFrom: '2023-05-24T02:00:10.000Z',
            reserveFromStoreDisabled: false,
            sendToStoreDisabled: false,
            personalDeliveryDisabled: false,
            estimatedArrivalDays: 3,
            productWithServiceFlag: false,
            dropShippingCategory: '0',
            originCountryCode: 'JP',
            flavorExpirationCategory: '0',
            flavorExpiration: 3,
            productCharacteristics:
              'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
            colorPattern: '黒',
            size: '',
            brandName: '',
            singleItemSizeWidth: 19.1,
            singleItemSizeHeight: 5.1,
            singleItemSizeDepth: 7.7,
            contentAmount: 10,
            contentAmountUnit: 'L',
            modelNo: '',
            lawsStandards: 'JIS',
            singleItemSize2Width: 19.1,
            singleItemSize2Height: 5.1,
            singleItemSize2Depth: 7.7,
            specCategory: [
              {
                name: 'カラー',
                value: '',
              },
              {
                name: '本体サイズ-幅(cm)',
                value: '19',
              },
              {
                name: '本体サイズ-奥行(cm)',
                value: '14.5',
              },
            ],
            characterCopyrightNameEc: '',
            longDescription:
              "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます",
            cautions:
              '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
            productSpecGroupId: '',
            similarProduct: '',
            recommendedProduct: '',
            comparativeProduct: '',
            kukuru: '00000152',
            variation: [
              {
                name: '01-001',
                value: '4',
              },
              {
                name: '01-001',
                value: '4',
              },
            ],
            faceProductId: '00000152',
            serviceContents: '',
            prices: [
              {
                productId: '4549509646945',
                storeCodes: '859',
                membershipRank: '4',
                priceIncludingTax: 8980,
                salePriceIncludingTax: 7980,
              },
              {
                productId: '4549509646945',
                storeCodes: '123',
                membershipRank: '4',
                priceIncludingTax: 8980,
                salePriceIncludingTax: 7980,
              },
            ],
            inventories: [
              {
                productId: '4549509646952',
                storeCode: '859',
                quantityOpening: 10,
                quantitySold: 3,
                quantityAvailable: 6,
                quantityAllocated: 1,
                quantityExpected: 3,
                expectedArrivalDate: '2023-03-03T00:00:00.000Z',
              },
              {
                productId: '4549509646952',
                storeCode: '123',
                quantityOpening: 10,
                quantitySold: 3,
                quantityAvailable: 6,
                quantityAllocated: 1,
                quantityExpected: 3,
              },
            ],
          },
          delivery: {
            shipping: {
              estimatedDate: '2023-06-23',
              canSelectDate: false,
              items: [
                {
                  productCode: '4549509524317',
                  estimatedDate: '2023-06-23',
                  isSeparate: false,
                },
              ],
            },
            pickup: {
              dateTime: '2023-06-23 09:08',
              items: [
                {
                  productCode: '4549509524317',
                  estimatedDate: '2023-06-23',
                  isSeparate: false,
                },
              ],
            },
          },
          setProductType: '0',
          isReserveFromStoreAvailable: true,
          isPersonalDeliveryAvailable: true,
          invalidWebBackOrderFlagForStorePickup: false,
          invalidWebBackOrderFlagForDesignatedDelivery: true,
          isWebBackOrder: false,
          unitPrice: 2000,
          subtotalProductAmount: 10000,
          individualShippingCost: 4000,
          subtotalIndividualShippingCost: 3200,
          campaignPoints: 1800,
          subtotalCampaignPoints: 3600,
          isCheckoutTarget: false,
          checkoutId: '123456',
          checkoutStatus: 'In-progress',
          createdAt: '2023-11-14T13:40:21+09:00',
          updatedAt: '2023-11-15T13:40:21+09:00',
        },
      ],
    },
  ],
  shippingProducts: [
    {
      productItems: [],
    },
  ],
  paymentAmountInfoArray: [
    {
      settlementType: '2',
      receivingMethod: '1',
      paymentMethodId: '1',
      totalProductAmount: 15000,
      basicShippingCost: 500,
      regionalShippingCost: 1700,
      totalIndividualShippingCost: 1500,
      paymentCharge: 330,
      redeemedPoints: 100,
      estimatedGrantedPoints: 68,
      estimatedGrantedCampaignPoints: 500,
      totalAmount: 18930,
      taxClassificationInfoArray: [
        {
          taxClassification: '1',
          taxClassificationName: '10% (通常税率)',
          taxableAmount: 19030,
          tax: 1730,
        },
        {
          taxClassification: '2',
          taxClassificationName: '8% (軽減税率)',
          taxableAmount: 1080,
          tax: 80,
        },
      ],
    },
  ],
  checkoutId: '74234354598',
  isAmazonPayOneTimePayment: true,
};
const mockCheckoutBeginDto = {
  userId: '48677635-ac6a-4412-8f68-5a933a166a29',
  amazonCheckoutSessionId: '12345',
  selectedItems: ['MlgzTxGMz9XWS4J81BB0', 'MlgzTxGMz9XWS4J81BB1'],
};
const userIdValidationError = new HttpException(
  {
    errorCode: ErrorCode.PARAM_BAD_PARAMETER_IS_WEB,
    message: 'parameter validation error:userId',
  },
  HttpStatus.BAD_REQUEST,
);
const MockcheckoutId = '10130759-c3fa-4136-a619-e30a4ec41aa7';
const MockcheckoutCompleteServiceData: any = {
  receptionId: '7573536222410',
  orderId: '4772713525',
  accessId: 'ohcOp.0*xD5vdeOYNEPDPHXbwXN9',
  token: 'wRgKytjCx/rk.CiOyoZIAjS4pENzgmGgxg9',
  paymentStartUrl: 'https://xxxx.mul-pay.jp/payment/DocomoStart.idPass',
  paymentStartBy: '2023-10-30T16:50:24.367Z',
};

const MockcheckoutCompleteBodyData: any = {
  userId: 'a3a2d619-e97c-4c68-8d29-2db0231250f6',
  customerInfo: {
    customerLastName: '埼玉',
    customerFirstName: '太郎',
    customerLastNameKana: 'サイタマ',
    customerFirstNameKana: 'サイタマ',
    customerPostalCode: '3670030',
    customerPrefecture: '埼玉県',
    customerCity: '埼玉県',
    customerAddress1: '本庄市早稲田の杜',
    customerAddress2: 'Cainsville',
    customerCompanyName: 'EC Replace Co., Ltd.',
    customerDepartmentName: 'Information System Department',
    customerPhone: '04811100000',
    customerEmail: 'bftest@bftest.com',
  },
  shippingInfo: {
    isSameAsPurchaser: false,
    selectedAddressBookId: '1',
    shippingLastName: '埼玉',
    shippingFirstName: '太郎',
    shippingLastNameKana: 'サイタマ',
    shippingFirstNameKana: 'タロウ',
    shippingPostalCode: '3670030',
    shippingPrefecture: '埼玉県',
    shippingCity: '埼玉県',
    shippingAddress1: '本庄市早稲田の杜',
    shippingAddress2: 'Akahira Mansion Room 1',
    shippingCompanyName: 'Hokkaido Co., Ltd.',
    shippingDepartmentName: 'Information System Department',
    shippingPhone: '04811100000',
    desiredDeliveryDate: '2023/12/20(Wed)',
    desiredDeliveryTimeZoneId: null,
    isDeliveryBox: false,
    isGift: true,
  },
  affiliateTrackingId: '123ABCdefg456HIJklm789NOPqrs789TUV',
  affiliateVisitDateTime: '2023-10-23T13:32:06Z',
  creditCardTokenList: null,
  httpHeader: null,
};
const MockcheckoutCompleteServiceOtherPaymentsData: any = {
  orderCompleteInfo: [
    {
      orderId: '4772713528',
      receptionId: '1117295780837',
      shortOrderId: '74272962',
      receivingMethod: '1',
      paymentMethodId: '3',
      convenienceCode: '10001',
      customerEmail: 'xxxxxxx@test.co.jp',
      isMember: true,
    },
  ],
};

const MockcheckoutCompleteServiceStoreData: any = {
  orderCompleteInfo: [
    {
      orderId: '4772713526',
      receptionId: '7680744034025',
      shortOrderId: '12988967',
      receivingMethod: '1',
      paymentMethodId: '2',
      convenienceCode: '00007',
      purchaseAmount: 3233,
      payBy: '2023-10-30T16:50:24.367Z',
      confirmationNumber: '2024',
      receiptNumber: 'LW233053476653',
      slipUrl: 'https://xxxxx.mul-pay.jp/seven/sample.html',
      clientField1: 'Free item 1',
      clientField2: 'Free item 2',
      clientField3: 'Free item 3',
      customerEmail: 'xxxxxxx@test.co.jp',
      isMember: true,
    },
  ],
};

const MockPayments: any = {
  data: {
    paymentMethodInfoList: [
      {
        paymentMethodId: '8',
        paymentMethodName: 'Deferred payment',
        paymentMethodDetail: 'gift card',
        registeredCreditCardList: [
          {
            cardSequentialNumber: 0,
            cardNumber: '999999****9999',
            expirationDate: '12/24',
            isDeleted: false,
            isSelected: false,
          },
        ],
        paymentCharge: 100,
        maxPurchaseAmount: 10000,
        isStorePaymentSelected: false,
        isSaveCard: false,
        numberOfTokensRequired: 5,
        errorCode: null,
        message: '',
      },
    ],
  },
};
const MockOtherPayments: any = {
  data: {
    paymentMethodInfoList: [
      {
        paymentMethodId: '3',
        paymentMethodName: 'GMO deferred payment',
        paymentMethodDetail: '',
        registeredCreditCardList: [
          {
            cardSequentialNumber: '',
            cardNumber: '',
            expirationDate: '',
            isDeleted: false,
            isSelected: true,
          },
        ],
        convenienceCodeList: [
          {
            convenienceCode: '00007',
            convenienceName: 'セブンイレブン',
            isSelected: false,
          },
        ],
        paymentCharge: 100,
        maxPurchaseAmount: 10000,
        isStorePaymentSelected: false,
        isSaveCard: false,
        numberOfTokensRequired: 5,
        errorCode: null,
        message: '',
      },
    ],
  },
};
const mockInternalServerError = new HttpException(
  {
    errorCode: ErrorCode.CART_FIRE_STORE_ERROR,
    message: CartErrorMessage[ErrorCode.CART_FIRE_STORE_ERROR],
  },
  HttpStatus.INTERNAL_SERVER_ERROR,
);

const mockCheckOutComplete2Id = '009b67fd-1c20-4f8d-94b1-d636ee8eaad1';
const mockCheckOutComplete2Dto: any = {
  userId: '12345',
  orderId: '19287341',
  shopId: '23112423',
  receptionId: '129847',
  status: 'AUTH',
  amazonChargePermissionID: '98796',
  checkString: '9689577',
  tranDate: '23-09-2023',
  errCode: null,
  errInfo: null,
};
const mockCheckoutComplete2Response: any = {
  orderId: '4772713525',
  paymentId: '123',
  accessId: 'bfe410dSFFJCv-5t1EcD7Odv7Dsn',
  token: 'C.GGPQxJSYpJpBUqUO4OO30.mcjIC5KAqJG',
  paymentStartUrl: 'https://cainz.com/amazon/payments',
  paymentStartBy: '2023-11-03T11:40:34.329Z',
};
const mockCheckoutComplete2Error = new HttpException(
  {
    code: GlobalErrorCode.BAD_PARAMETER,
    message: `Checkout ID Not Found`,
    errorCode: GlobalErrorCode.BAD_PARAMETER,
  },
  HttpStatus.BAD_REQUEST,
);
const mockInternalServerErrorCheckout = new HttpException(
  {
    errorCode: ErrorCode.CHECKOUT_FIRE_STORE_ERROR,
    message: CheckoutErrorMessage[ErrorCode.CHECKOUT_FIRE_STORE_ERROR],
  },
  HttpStatus.INTERNAL_SERVER_ERROR,
);
const mockcheckoutId = '009b67fd-1c20-4f8d-94b1-d636ee8eaad1';
const mockCheckOutChangeData: any = {
  userId: '07P1He8a0Ze4OlTCpWf3D3M469P1',
  customerInfo: {
    customerZipCode: '3670068',
    customerPrefecture: '埼玉県',
    customerCity: '本庄市早稲田の杜',
  },
  selectedStoreCode: '0986',
  redeemedPoints: 2,
};

const mockCheckoutChangeWithoutUserIdData: any = {
  customerInfo: {
    customerZipCode: '3670068',
    customerPrefecture: '埼玉県',
    customerCity: '本庄市早稲田の杜',
  },
  selectedStoreCode: '0986',
  redeemedPoints: 2,
};
export {
  mockInternalServerError,
  MockPayments,
  MockcheckoutId,
  MockcheckoutCompleteServiceData,
  MockcheckoutCompleteBodyData,
  MockcheckoutCompleteServiceStoreData,
  MockcheckoutCompleteServiceOtherPaymentsData,
  mockCheckoutBeginResponse,
  mockCheckoutBeginDto,
  userIdValidationError,
  mockCheckoutComplete2Response,
  mockCheckoutComplete2Error,
  mockCheckOutComplete2Dto,
  mockCheckOutComplete2Id,
  mockInternalServerErrorCheckout,
  mockCheckOutChangeData,
  mockcheckoutId,
  mockCheckoutChangeWithoutUserIdData,
};
