export enum OnlineSalesType {
  ONLINESALESTYPE_EC = '1',
  ONLINESALESTYPE_DIRECTLY_MANUFACTURER = '2',
  ONLINESALESTYPE_MANUFACTURER_ORDERING = '3',
  ONLINESALESTYPE_STORE_INVENTORY = '4',
}

export enum DropshipCategory {
  DROPSHIP_PRODUCT_TYPE = '1',
  DROPSHIP_PRODUCT_TYPE_MARKETPLACE1 = '2',
  DROPSHIP_PRODUCT_TYPE_MARKETPLACE2 = '3',
}

export enum ReceivingMethod {
  DELIVERY_TO_DESIGNATED_ADDRESS = '1',
  PICKUP_AT_STORE = '2',
}

export enum DeliveryChargeCategoryEc {
  FREE_SHIPPING = '1',
  STANDARD_SHIPPING_FEE = '2',
  INDIVIDUAL_SHIPPING_FEE = '3',
  FLAT_RATE_SHIPPING = '4',
  FREE_BASIC_SHIPPING = '5',
  FREE_SHIPPING_ON_ALL_ITEMS = '6',
}

export enum StoreCodes {
  EC_STORECODE = '888',
}

export enum ReceiptMethod {
  DELIVERY_TO_DESIGNATED_ADDRESS_ONLY = 1,
  PICKUP_AT_STORE_ONLY = 2,
  BOTH = 3,
  NOT_APPLICABLE = 9,
}
