steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['run', 'test', '--', '--scope', '${_SCOPE}']
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-f',
        '$_DOCKER_FILE',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
        '--build-arg',
        'SERVICE_NAME=${_SERVICE_NAME}',
        '--build-arg',
        'ENV_CONFIG_FILE_NAME=${_ENV_CONFIG_FILE_NAME}',
        '.',
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
      ]
  # NOTE:`bash -c`を利用しない配列で書くパターンだと、Secret経由の環境変数を埋め込めなかった
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
        --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
        --region ${_LOCATION} \
        --allow-unauthenticated \
        --set-env-vars=PROJECT_ID=$PROJECT_ID \
        --set-env-vars=CRYPTO_KEY=$$CRYPTO_KEY \
        --set-env-vars=CRYPTO_IV=$$CRYPTO_IV \
        --set-env-vars=CAINZAPP_API_KEY=$$CAINZAPP_API_KEY
    secretEnv: ['CRYPTO_KEY', 'CRYPTO_IV', 'CAINZAPP_API_KEY']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    args:
      [
        'gcloud',
        'builds',
        'triggers',
        'run',
        '${_E2E_TRIGGER_NAME}',
        '--branch=${BRANCH_NAME}',
        '--project=${PROJECT_ID}',
        '--region=${_LOCATION}',
      ]
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
substitutions:
  _SERVICE_NAME: 'checkout'
  _DOCKER_FILE: 'apps/api/checkout/Dockerfile'
  _ENV_CONFIG_FILE_NAME: '.env.dev'
  _CLOUD_BUILD_REPOSITORY: 'backend'
  _NODE_VERSION: '18.16.0'
  _SCOPE: 'checkout'
  _LOCATION: 'asia-northeast1'
  _E2E_TRIGGER_NAME: 'checkout-e2e'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/crypto_key/versions/latest
      env: 'CRYPTO_KEY'
    - versionName: projects/$PROJECT_ID/secrets/crypto_iv/versions/latest
      env: 'CRYPTO_IV'
    - versionName: projects/$PROJECT_ID/secrets/cainzapp_api_key/versions/latest
      env: 'CAINZAPP_API_KEY'
