const checkoutBeginResponse = {
  customerInfo: {
    customerLastName: '埼玉',
    customerFirstName: '太郎',
    customerLastNameKana: 'サイタマ',
    customerFirstNameKana: 'タロウ',
    customerZipCode: '3671234',
    customerPrefecture: '埼玉県',
    customerCity: '本庄市',
    customerAddress1: '早稲田の杜一丁目９９番９９９号',
    customerAddress2: 'カインズビル',
    customerCompanyName: '株式会社　ECリプレイス',
    customerDepartmentName: '情報システム部',
    customerPhone: '0120999999',
    customerEmail: 'Taro@test.co.jp',
  },
  storeInfo: {
    storeCode: '0760',
    storeName: 'カインズ伊勢崎',
    storeHours: '09:00 ～ 20:00',
    zipCode: '3720999',
    address: '群馬県伊勢崎市宮子町９９９９',
    supportPickupInnerLocker: true,
    supportPickupPlace: true,
    supportPickupPlaceParking: true,
    selectedReceiptLocation: '3',
    supportCredit: true,
    mapUrl: 'https://map.test.com/map/999',
    estimatedPickupableDateTime: '本日 11/16(木) 最短13:00以降受取可',
  },
  addressBookList: [
    {
      addressBookId: '1',
      lastName: '配送先',
      firstName: '太郎',
      lastNameKana: 'ハイソウサキ',
      firstNameKana: 'タロウ',
      zipCode: '5300000',
      prefecture: '大阪府',
      city: '大阪市北区',
      address1: '梅田一丁目',
      address2: '梅田ビル９９階',
      companyName: 'テスト株式会社',
      departmentName: 'テスト部',
      phone: '069999999',
      isPreferredAddress: true,
      isSelected: true,
    },
  ],
  shippingInfo: {
    shippingLastName: 'お届け先',
    shippingFirstName: '太郎',
    shippingLastNameKana: 'オトドケサキ',
    shippingFirstNameKana: 'タロウ',
    shippingZipCode: '0790000',
    shippingPrefecture: '北海道',
    shippingCity: '赤平市',
    shippingAddress1: '赤平１１１丁目',
    shippingAddress2: '赤平マンション１号室',
    shippingCompanyName: '株式会社　北海道',
    shippingDepartmentName: '情報システム部',
    shippingPhone: '12599999999',
    selectedAddressBookId: '2',
    desiredDeliveryDateList: [
      {
        availableDeliveryDate: '2023-11-17T18:00:00.000Z',
        isSelected: false,
      },
      {
        availableDeliveryDate: '2023-11-18T18:00:00.000Z',
        isSelected: true,
      },
    ],
    desiredDeliveryTimeZoneList: [
      {
        availableDeliveryTimeZoneId: '0',
        availableDeliveryTimeZoneName: '14～16時',
        isSelected: true,
      },
    ],
    isDeliveryBox: false,
    isGift: false,
  },
  paymentMethodInfoList: [
    {
      paymentMethodId: '1',
      paymentMethodName: 'クレジットカード',
      paymentMethodDetail: 'ギフトカード',
      registeredCreditCardList: [
        {
          cardSequentialNumber: 0,
          cardNumber: '999999****9999',
          expirationDate: '12/24',
          isDeleted: false,
          isSelected: false,
        },
        {
          cardSequentialNumber: 1,
          cardNumber: '999999****8888',
          expirationDate: '01/26',
          isDeleted: false,
          isSelected: true,
        },
      ],
      convenienceCodeList: [
        {
          convenienceCode: '00007',
          convenienceName: 'セブンイレブン',
          isSelected: false,
        },
      ],
      paymentCharge: 330,
      maxPurchaseAmount: 55000,
      isStorePaymentSelected: false,
      isSaveCard: true,
      numberOfTokensRequired: 2,
      isSelected: true,
    },
  ],
  pointInfo: {
    availablePoints: 1000,
    redeemedPoints: 123,
  },
  storeReceiveProducts: [
    {
      productItems: [],
    },
  ],
  shippingProducts: [
    {
      productItems: [],
    },
  ],
  paymentAmountInfoArray: [
    {
      settlementType: '2',
      receivingMethod: '1',
      paymentMethodId: '1',
      totalProductAmount: 15000,
      basicShippingCost: 500,
      regionalShippingCost: 1700,
      totalIndividualShippingCost: 1500,
      paymentCharge: 330,
      redeemedPoints: 100,
      estimatedGrantedPoints: 68,
      estimatedGrantedCampaignPoints: 500,
      totalAmount: 18930,
      taxClassificationInfoArray: [
        {
          taxClassification: '1',
          taxClassificationName: '10% (通常税率)',
          taxableAmount: 19030,
          tax: 1730,
        },
        {
          taxClassification: '2',
          taxClassificationName: '8% (軽減税率)',
          taxableAmount: 1080,
          tax: 80,
        },
      ],
    },
  ],
  checkoutId: '74234354598',
  isAmazonPayOneTimePayment: true,
};

const productItem = {
  itemId: '',
  receivingMethod: '1',
  productId: '',
  quantity: 20,
  orderSpecification: {
    simulationNumber: '980089',
    height: 90,
    width: 200,
    hook: 'A',
  },
  product: {
    productId: '4549509646952',
    name: 'ロング丈も掛けられる折りたたみランドリーラックパタラン',
    categoryId: 'c2320',
    imageUrls: [
      'https://imgix.cainz.com/4549509646952/product/4549509646952_01.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_02.jpg',
      'https://imgix.cainz.com/4549509646952/product/4549509646952_03.jpg',
    ],
    departmentCode: '014',
    lineCode: '221',
    classCode: '1400',
    description: '',
    applicableStartDate: '2023-05-24T02:00:10.000Z',
    salesStartDate: '2023-05-24T02:00:10.000Z',
    consumptionTaxRate: 10,
    consumptionTaxCategory: '',
    salesEndDate: '2023-05-24T02:00:10.000Z',
    salesEndFlag: false,
    designatedPharmaceuticalCategory: '0',
    liquorCategory: '0',
    tobaccoCategory: '0',
    hazardousMaterialFlag: false,
    medicalEquipmentClass: '',
    poisonousDeleteriousSubstanceCategory: '0',
    poisonousDrugCategory: '0',
    agriculturalChemicalCategory: '0',
    animalDrugCategory: '0',
    warrantyIssuanceCategory: '0',
    pharmaceuticalFlag: false,
    salesTypeCategory: '0',
    warrantyCategory: '0',
    warrantyPeriod: '1年間',
    deliveryChargeCategoryEc: '0',
    onlineFlagEc: true,
    onlineStartTimeEc: '2023-05-24T02:00:10.000Z',
    onlineEndTimeEc: '2023-05-24T02:00:10.000Z',
    consumptionTaxCategoryEc: '0',
    onlineSalesCategoryEc: '0',
    individualDeliveryChargeEc: 600,
    setProductFlag: false,
    configurationFlag: false,
    customizedProductCategory: '0',
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    stepQuantity: 1,
    storeMinOrderQuantity: 1,
    storeMaxOrderQuantity: 100,
    storeStepOrderQuantity: 1,
    newPeriodFrom: '2023-05-24T02:00:10.000Z',
    reserveFromStoreDisabled: false,
    sendToStoreDisabled: false,
    personalDeliveryDisabled: false,
    estimatedArrivalDays: 3,
    productWithServiceFlag: false,
    dropShippingCategory: '0',
    originCountryCode: 'JP',
    flavorExpirationCategory: '0',
    flavorExpiration: 3,
    productCharacteristics:
      'ワンピースも干せる。超軽量＆収納時はコンパクト。風が通りやすい設計で乾きやすい',
    colorPattern: '黒',
    size: '',
    brandName: '',
    singleItemSizeWidth: 19.1,
    singleItemSizeHeight: 5.1,
    singleItemSizeDepth: 7.7,
    contentAmount: 10,
    contentAmountUnit: 'L',
    modelNo: '',
    lawsStandards: 'JIS',
    singleItemSize2Width: 19.1,
    singleItemSize2Height: 5.1,
    singleItemSize2Depth: 7.7,
    specCategory: [
      {
        name: 'カラー',
        value: '',
      },
      {
        name: '本体サイズ-幅(cm)',
        value: '19',
      },
      {
        name: '本体サイズ-奥行(cm)',
        value: '14.5',
      },
    ],
    characterCopyrightNameEc: '',
    longDescription:
      "大人気リピーター続出!カインズPet'sOneの猫砂がおすすめ! 固まった部分は水洗トイレに流すことができます。使用上の注意をよくお読みください。おからが主原料なので燃やすことができます。生ごみとしても処理できます。",
    cautions: '◆お届けの時期により、パッケージ（箱）が異なる場合がございます。',
    productSpecGroupId: '',
    similarProduct: '',
    recommendedProduct: '',
    comparativeProduct: '',
    kukuru: '00000152',
    variation: [
      {
        name: '01-001',
        value: '4',
      },
      {
        name: '01-001',
        value: '4',
      },
    ],
    faceProductId: '00000152',
    serviceContents: '',
    prices: [
      {
        productId: '4549509646945',
        storeCodes: '859',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
      {
        productId: '4549509646945',
        storeCodes: '123',
        membershipRank: '4',
        priceIncludingTax: 8980,
        salePriceIncludingTax: 7980,
      },
    ],
    inventories: [
      {
        productId: '4549509646952',
        storeCode: '859',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
        expectedArrivalDate: '2023-03-03T00:00:00.000Z',
      },
      {
        productId: '4549509646952',
        storeCode: '123',
        quantityOpening: 10,
        quantitySold: 3,
        quantityAvailable: 6,
        quantityAllocated: 1,
        quantityExpected: 3,
      },
    ],
  },
  delivery: {
    shipping: {
      estimatedDate: '2023-06-23',
      canSelectDate: false,
      items: [
        {
          productCode: '4549509524317',
          estimatedDate: '2023-06-23',
          isSeparate: false,
        },
      ],
    },
    pickup: {
      dateTime: '2023-06-23 09:07',
      items: [
        {
          productCode: '4549509524317',
          estimatedDate: '2023-06-23',
          isSeparate: false,
        },
      ],
    },
  },
  setProductType: '0',
  isReserveFromStoreAvailable: true,
  isPersonalDeliveryAvailable: true,
  invalidWebBackOrderFlagForStorePickup: false,
  invalidWebBackOrderFlagForDesignatedDelivery: true,
  isWebBackOrder: false,
  unitPrice: 2000,
  subtotalProductAmount: 10000,
  individualShippingCost: 4000,
  subtotalIndividualShippingCost: 3200,
  campaignPoints: 1800,
  subtotalCampaignPoints: 3600,
  isCheckoutTarget: false,
  checkoutId: '123456',
  checkoutStatus: 'Completed',
  createdAt: '2023-11-14T13:40:20+07:21',
  updatedAt: '2023-11-15T13:40:21+09:00',
};

export { checkoutBeginResponse, productItem };
