steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['run', 'test:e2e', '--', '--scope', '${_SCOPE}']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'E2E_TEST_BASE_URL=https://user-eqqsu5fmdq-an.a.run.app/v1/users'
    secretEnv: ['feraAPP_API_KEY']
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _NODE_VERSION: '18.16.0'
  _SCOPE: 'user'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/feraapp_api_key/versions/latest
      env: 'feraAPP_API_KEY'
