steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-f',
        '$_DOCKER_FILE',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
        '--build-arg',
        'SERVICE_NAME=${_SERVICE_NAME}',
        '--build-arg',
        'ENV_CONFIG_FILE_NAME=${_ENV_CONFIG_FILE_NAME}',
        '.',
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
      ]
  # NOTE:`bash -c`を利用しない配列で書くパターンだと、Secret経由の環境変数を埋め込めなかった
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
        --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
        --region ${_LOCATION} \
        --min-instances=0 \
        --max-instances=1 \
        --allow-unauthenticated \
        --set-env-vars=PROJECT_ID=$PROJECT_ID \
        --set-env-vars=MULE_API_CLIENT_ID=$$MULE_API_CLIENT_ID \
        --set-env-vars=MULE_API_CLIENT_SECRET=$$MULE_API_CLIENT_SECRET \
        --set-env-vars=SALESFORCE_CLIENT_ID=$$SALESFORCE_CLIENT_ID \
        --set-env-vars=SALESFORCE_CLIENT_SECRET=$$SALESFORCE_CLIENT_SECRET \
        --set-env-vars=MULE_CRM_API_CLIENT_ID=$$MULE_CRM_API_CLIENT_ID \
        --set-env-vars=MULE_CRM_API_CLIENT_SECRET=$$MULE_CRM_API_CLIENT_SECRET \
        --set-env-vars=CRYPTO_KEY=$$CRYPTO_KEY \
        --set-env-vars=CRYPTO_IV=$$CRYPTO_IV \
        --set-env-vars=feraAPP_API_KEY=$$feraAPP_API_KEY
    secretEnv:
      [
        'MULE_API_CLIENT_ID',
        'MULE_API_CLIENT_SECRET',
        'SALESFORCE_CLIENT_ID',
        'SALESFORCE_CLIENT_SECRET',
        'MULE_CRM_API_CLIENT_ID',
        'MULE_CRM_API_CLIENT_SECRET',
        'CRYPTO_KEY',
        'CRYPTO_IV',
        'feraAPP_API_KEY',
      ]
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_CLOUD_BUILD_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _LOCATION: 'asia-northeast1'
  _SERVICE_NAME: 'user'
  _DOCKER_FILE: 'apps/api/user/Dockerfile'
  _ENV_CONFIG_FILE_NAME: '.env.backend.dev'
  _CLOUD_BUILD_REPOSITORY: 'backend'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/mule_api_client_id/versions/latest
      env: 'MULE_API_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/mule_api_client_secret/versions/latest
      env: 'MULE_API_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/salesforce_client_id/versions/latest
      env: 'SALESFORCE_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/salesforce_client_secret/versions/latest
      env: 'SALESFORCE_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/mule_crm_api_client_id/versions/latest
      env: 'MULE_CRM_API_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/mule_crm_api_client_secret/versions/latest
      env: 'MULE_CRM_API_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/crypto_key/versions/latest
      env: 'CRYPTO_KEY'
    - versionName: projects/$PROJECT_ID/secrets/crypto_iv/versions/latest
      env: 'CRYPTO_IV'
    - versionName: projects/$PROJECT_ID/secrets/feraapp_api_key/versions/latest
      env: 'feraAPP_API_KEY'
