steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['run', 'test:e2e', '--', '--scope', '${_SCOPE}']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'E2E_TEST_BASE_URL=https://pocketregi-eqqsu5fmdq-an.a.run.app/v1/pocketregi'
    secretEnv: ['CAINZAPP_API_KEY']
substitutions:
  _NODE_VERSION: '18.16.0'
  _SCOPE: 'pocketregi'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/cainzapp_api_key/versions/latest
      env: 'CAINZAPP_API_KEY'
